#!/usr/bin/env bash
# BetterTrack Multi-Factory — Autorun launcher (run on the HOST).
#
#   ./multi-factory/autorun.sh            # build + start master and N workers, detached
#   ./multi-factory/autorun.sh --dry      # start in MF_DRY_RUN=1 mode (no LLM calls)
#   ./multi-factory/autorun.sh --logs     # follow all container logs
#   ./multi-factory/autorun.sh --stop     # stop containers (resume later with autorun.sh)
#   ./multi-factory/autorun.sh --down     # stop AND remove containers (state/ dir persists)
#   ./multi-factory/autorun.sh --fresh    # wipe protocol state + clone volumes, start clean
#   ./multi-factory/autorun.sh --self-test # run the offline guard suite only, then exit
#
# The single factory and the multi-factory must NEVER run at the same time against
# the repo — both launchers refuse to start while the other project has containers.
# Prefer the control dashboard (multi-factory/control/) for day-to-day start/stop/
# pause/run-out/close-down.
set -euo pipefail
cd "$(dirname "$0")"

if docker info >/dev/null 2>&1; then DOCKER=docker; else DOCKER="sudo docker"; fi

# Worker count: env override > state/control/workers (dashboard-set) > 2.
# 2 is the sweet spot (api + web lanes); >2 pays only with more open lanes; hard cap 4.
WORKERS=${WORKERS:-$(cat state/control/workers 2>/dev/null || echo 2)}
case "$WORKERS" in 1|2|3|4) ;; *) echo "! invalid workers '$WORKERS' — using 2"; WORKERS=2;; esac
export WORKERS
MF_COMPOSE_PROJECT=bettertrack-multifactory
COMPOSE_FILES=(-f compose.yml)
if [ -n "${MF_COMPOSE_OVERRIDE:-}" ]; then
  [ -f "$MF_COMPOSE_OVERRIDE" ] || {
    echo "✗ MF_COMPOSE_OVERRIDE must name one existing Compose file"
    exit 1
  }
  OVERRIDE_DIR=$(cd "$(dirname "$MF_COMPOSE_OVERRIDE")" && pwd -P)
  OVERRIDE_FILE="$OVERRIDE_DIR/$(basename "$MF_COMPOSE_OVERRIDE")"
  COMPOSE_FILES+=(-f "$OVERRIDE_FILE")
fi
if [ "$WORKERS" -gt 2 ]; then
  {
    echo "# GENERATED by autorun.sh for WORKERS=$WORKERS — do not edit, not committed."
    echo "services:"
    w=3
    while [ "$w" -le "$WORKERS" ]; do
      cat <<EXTRA
  worker-$w:
    build: ../factory
    env_file: ../factory/.env
    restart: unless-stopped
    entrypoint: ['bash', '/work/mf/worker.sh']
    environment:
      FACTORY_NAME: multi
      WORKERS: \${WORKERS:-2}
      MF_DRY_RUN: \${MF_DRY_RUN:-0}
      MF_MODELS_FILE: \${MF_MODELS_FILE:-/work/mfstate/control/models.json}
      CCR_HOME: /home/factory/.claude-code-router
      MF_CLAUDE_TOKEN_FILE: /home/factory/.claude-auth/oauth-token
      MF_CLAUDE_PROFILE_FILE: /home/factory/.claude-auth/profile.json
      MF_CLAUDE_PROFILE_REQUIRED: '1'
      MF_OPENCODE_HOME: /home/factory/.opencode
      MF_OPENCODE_CONFIG: /work/mf/opencode-factory.json
      WORKER_ID: '$w'
    volumes:
      - mf-w$w-work:/work/state
      - ./state:/work/mfstate
      - ./worker.sh:/work/mf/worker.sh:ro
      - ./mflib.sh:/work/mf/mflib.sh:ro
      - ./contracts.sh:/work/mf/contracts.sh:ro
      - ./create-issue.sh:/work/mf/create-issue.sh:ro
      - ./ccr-common.mjs:/work/mf/ccr-common.mjs:ro
      - ./ccr-bootstrap.mjs:/work/mf/ccr-bootstrap.mjs:ro
      - ./ccr-ensure.mjs:/work/mf/ccr-ensure.mjs:ro
      - ./claudex-direct-probe.mjs:/work/mf/claudex-direct-probe.mjs:ro
      - ./claudex-redact.mjs:/work/mf/claudex-redact.mjs:ro
      - ./provider-test.sh:/work/mf/provider-test.sh:ro
      - ./opencode-factory.json:/work/mf/opencode-factory.json:ro
      - ../factory/lib.sh:/work/mf/lib.sh:ro
      - ../factory/prompts:/work/state/prompts:ro
      - ./prompts:/work/state/mf-prompts:ro
      - ../factory/usage:/work/usage
      - ./auth/worker-$w/claude:/home/factory/.claude-auth:ro
      - ./auth/worker-$w/codex:/home/factory/.codex
      - ./auth/worker-$w/ccr:/home/factory/.claude-code-router
      - ./auth/worker-$w/opencode:/home/factory/.opencode
EXTRA
      w=$((w+1))
    done
    echo "volumes:"
    w=3
    while [ "$w" -le "$WORKERS" ]; do echo "  mf-w$w-work:"; w=$((w+1)); done
  } > compose.extra.yml
  COMPOSE_FILES+=(-f compose.extra.yml)
fi
# Every lifecycle path goes through one helper. The explicit project name wins
# over both a Compose file's top-level `name:` and an inherited
# COMPOSE_PROJECT_NAME; unsetting the latter also keeps it out of interpolation.
dc(){
  env -u COMPOSE_PROJECT_NAME \
    $DOCKER compose --project-name "$MF_COMPOSE_PROJECT" \
    "${COMPOSE_FILES[@]}" "$@"
}

require_env(){
  [ -f ../factory/.env ] || { echo "✗ factory/.env missing. Copy .env.example → .env and fill the tokens."; exit 1; }
}

# docker ps lists running AND paused containers, so a paused single factory blocks too.
guard_single_factory(){
  if [ -n "$($DOCKER ps -q --filter label=com.docker.compose.project=bettertrack-factory)" ]; then
    echo "✗ The single factory (bettertrack-factory) is running/paused."
    echo "  The two factories must never run at the same time against the repo."
    echo "  Stop it first:  ./factory/autorun.sh --stop"
    exit 1
  fi
}

# Copy provider CLI credentials from the host into gitignored PER-CONTAINER dirs
# (multi-factory/auth/<service>/…) that compose bind-mounts over the container
# HOME. Per-container copies keep token-refresh writes from racing across
# containers; a copy is only overwritten when the host file is NEWER (so a
# container-refreshed token survives restarts while a fresh host login wins).
# Missing host auth is a warning, not an error — that provider simply reports
# unavailable until the owner logs in on the host and restarts.
sync_file(){ # $1=src $2=dst
  [ -f "$1" ] || return 0
  if [ ! -f "$2" ] || [ "$1" -nt "$2" ]; then cp -f "$1" "$2" && chmod 600 "$2"; fi
}
# opencode keeps its credential in a plain JSON keystore (auth.json). Unlike the
# other providers this is an API KEY, not a refreshable subscription token, so
# there is nothing for the container to write back — the host copy is always
# authoritative and sync_file's "newer wins" rule is a no-op in practice.
#
# The owner's isolated opencode sandbox is the source of truth for that keystore
# because the host user account may also run opencode interactively with a
# different (or no) key. OPENCODE_AUTH_SRC overrides it.
OPENCODE_AUTH_SRC=${OPENCODE_AUTH_SRC:-$HOME/.bettertrack-factory/opencode-sandbox/home/.local/share/opencode/auth.json}
# Warm the models.dev catalog from the host. This is ONLY a cold-start warm-up:
# opencode replaces this file with its own fetch on the first run, and that
# in-container fetch has been observed returning a SHORT catalog (176 vs 367
# entries) that omits preview models. The authoritative fix is therefore the
# explicit provider.openrouter.models block in opencode-factory.json, which is
# bind-mounted read-only and cannot be overwritten. Do not rely on this copy.
OPENCODE_MODELS_SRC=${OPENCODE_MODELS_SRC:-$HOME/.bettertrack-factory/opencode-sandbox/home/.cache/opencode/models.json}
opencode_authed(){ [ -s "$OPENCODE_AUTH_SRC" ]; }

sync_provider_auth(){
  local services="master" w c
  for w in $(seq 1 "$WORKERS"); do services="$services worker-$w"; done
  for c in $services; do
    mkdir -p "auth/$c/claude" "auth/$c/codex" "auth/$c/ccr" \
      "auth/$c/opencode/share/opencode" "auth/$c/opencode/cache/opencode" \
      "auth/$c/opencode/config"
    chmod 700 "auth/$c/claude" "auth/$c/codex" "auth/$c/ccr" \
      "auth/$c/opencode" 2>/dev/null || true
    # codex (ChatGPT subscription): auth.json is the credential; config.toml is
    # GENERATED for the container (trust the factory clone), never copied.
    sync_file "$HOME/.codex/auth.json" "auth/$c/codex/auth.json"
    sync_file "$HOME/.codex/models_cache.json" "auth/$c/codex/models_cache.json"
    printf '[projects."/work/state/repo"]\ntrust_level = "trusted"\n' > "auth/$c/codex/config.toml"
    chmod 600 "auth/$c/codex/config.toml"
    # ClaudeX has one private, writable CCR home per service. It imports from
    # that service's Codex copy at runtime; host CCR databases are never copied.
    # opencode (OpenRouter API key): one keystore per container, mode 600. The
    # container mounts auth/$c/opencode at $MF_OPENCODE_HOME and mflib.sh points
    # opencode's three XDG dirs inside it, so share/opencode/auth.json is exactly
    # where opencode looks. Never echoed, never committed (auth/ is gitignored).
    sync_file "$OPENCODE_AUTH_SRC"   "auth/$c/opencode/share/opencode/auth.json"
    sync_file "$OPENCODE_MODELS_SRC" "auth/$c/opencode/cache/opencode/models.json"
  done
  chmod -R go-rwx auth 2>/dev/null || true
  [ -f "$HOME/.codex/auth.json" ] || echo "! codex auth not found (~/.codex/auth.json) — codex provider unavailable until 'codex login' on the host"
  if ! opencode_authed; then
    echo "! opencode auth not found ($OPENCODE_AUTH_SRC) — opencode provider unavailable."
    echo "  Create it once on the host (the key is never printed or committed):"
    echo "    HOME=\$HOME/.bettertrack-factory/opencode-sandbox/home opencode auth login"
  fi
}

# Named Claude setup-token profiles are stored separately from their
# service-local materializations. The Node helper owns validation, atomic
# writes, and permissions; autorun only asks it to resolve the configured
# master/worker assignments before Compose mounts those directories.
sync_claude_profiles(){
  node control/claude-credential-sync.mjs "$WORKERS"
}

prepare_state(){
  mkdir -p state/assignments state/status state/merge-queue state/control state/logs prompts
  rm -f state/STOP state/control/dry-done
  sync_provider_auth
  sync_claude_profiles
  # Drop protocol files of workers beyond the configured count so the master
  # never assigns to a container that will not start.
  for f in state/assignments/worker-*.json state/status/worker-*.json state/status/worker-*.hb; do
    [ -e "$f" ] || continue
    id=$(basename "$f" | sed 's/worker-\([0-9]*\).*/\1/')
    [ -n "$id" ] && [ "$id" -gt "$WORKERS" ] && rm -f "$f"
  done
  # (Re)starting the factory means: run. Drain modes are set via control/mode later.
  printf 'run\n' > state/control/mode.tmp && mv -f state/control/mode.tmp state/control/mode
}

# The offline guard suite. No Docker, no network, no tokens: test.sh stubs `gh`,
# drives the deterministic scheduler/composer/merger core out of a temp state dir
# and chains protocol-test.sh, claudex-test.sh and the control-plane Node tests.
# Runs on every start (skippable with MF_SKIP_SELF_TEST=1) so a guard regression
# is caught before the fleet is armed, and leaves state/logs/test-<ts>.log behind
# as the evidence that the suite actually ran on this deploy.
self_test(){ # $1=fatal (1 = a failing suite stops the deploy)
  local fatal=${1:-0} stamp log rc=0
  mkdir -p state/logs
  stamp=$(date -u +%Y%m%dT%H%M%SZ)
  log=state/logs/test-$stamp.log
  echo "→ running the offline guard suite (./multi-factory/test.sh) → $log"
  # Nested guard: claudex-test.sh drives this very script with a stubbed docker,
  # and an unguarded start path would recurse into the suite forever.
  MF_SKIP_SELF_TEST=1 ./test.sh >"$log" 2>&1 || rc=$?
  # One summary line per chained suite (scheduler, protocol, ClaudeX, control).
  grep -hE '^(passed|protocol passed|ClaudeX passed):|^# (pass|fail) [0-9]+$' "$log" || true
  if [ "$rc" -eq 0 ]; then
    echo "✓ guard suite passed"
  else
    echo "✗ guard suite FAILED (rc=$rc) — see $log"
    grep -h '✗' "$log" | head -20 || true
    [ "$fatal" -eq 1 ] && return 1
  fi
  return 0
}

case "${1:-up}" in
  --self-test) self_test 1 || exit 1; exit 0 ;;
  --logs)  dc logs -f; exit $? ;;
  --stop)  echo "→ stopping multi-factory"; dc stop; echo "✓ stopped. Resume with: ./multi-factory/autorun.sh"; exit 0 ;;
  --down)  echo "→ downing multi-factory"; dc down --remove-orphans; echo "✓ removed (state/ and clone volumes kept)"; exit 0 ;;
  --fresh) require_env; guard_single_factory
           echo "→ wiping multi-factory state + clone volumes"
           dc down -v --remove-orphans 2>/dev/null || true
           rm -rf state; prepare_state ;;
  --dry)   require_env; guard_single_factory; prepare_state
           echo "→ building image…"; dc build
           echo "→ starting multi-factory in DRY-RUN mode (no LLM calls)…"
           MF_DRY_RUN=1 dc up -d --force-recreate
           dc ps; exit 0 ;;
  up|"")   require_env; guard_single_factory; prepare_state ;;
  *) echo "usage: autorun.sh [--dry|--logs|--stop|--down|--fresh|--self-test]"; exit 1 ;;
esac

# Deploy-time evidence that the guards still hold. Non-fatal: a red suite must be
# loud, but it must not be able to keep the fleet down.
[ "${MF_SKIP_SELF_TEST:-0}" = 1 ] || self_test 0

echo "→ building image…"
dc build
echo "→ starting multi-factory (detached, restart=unless-stopped, workers=$WORKERS)…"
if [ "$WORKERS" = 1 ]; then
  MF_DRY_RUN=${MF_DRY_RUN:-0} dc up -d --force-recreate --remove-orphans master worker-1
else
  MF_DRY_RUN=${MF_DRY_RUN:-0} dc up -d --force-recreate --remove-orphans
fi
sleep 2
dc ps
cat <<'EOF'

✓ Multi-factory running: 1 master (composer → scheduler → merger) + workers.

  Dashboard:  node multi-factory/control/server.mjs   →  http://10.0.0.4:8790 (LAN)
  Watch:      ./multi-factory/autorun.sh --logs
  Stop:       ./multi-factory/autorun.sh --stop        (hard, resumable)
  Drain:      echo run-out    > multi-factory/state/control/mode   (finish ALL open issues, then idle)
              echo close-down > multi-factory/state/control/mode   (finish in-flight only, then idle)
  Pause:      docker compose -p bettertrack-multifactory pause / unpause
EOF
