#!/usr/bin/env bash
# BetterTrack Multi-Factory — Autorun launcher (run on the HOST).
#
#   ./multi-factory/autorun.sh            # build + start master and N workers, detached
#   ./multi-factory/autorun.sh --dry      # start in MF_DRY_RUN=1 mode (no LLM calls)
#   ./multi-factory/autorun.sh --logs     # follow all container logs
#   ./multi-factory/autorun.sh --stop     # stop containers (resume later with autorun.sh)
#   ./multi-factory/autorun.sh --down     # stop AND remove containers (state/ dir persists)
#   ./multi-factory/autorun.sh --fresh    # wipe protocol state + clone volumes, start clean
#
# The single factory and the multi-factory must NEVER run at the same time against
# the repo — both launchers refuse to start while the other project has containers.
# Prefer the control dashboard (multi-factory/control/) for day-to-day start/stop/
# pause/run-out/close-down.
set -euo pipefail
cd "$(dirname "$0")"

if docker info >/dev/null 2>&1; then DOCKER=docker; else DOCKER="sudo docker"; fi

# Worker count: env override > state/control/workers (dashboard-set) > 2.
# 2 is the sweet spot (api + web lanes); >2 pays only with more open lanes; hard cap 4.
WORKERS=${WORKERS:-$(cat state/control/workers 2>/dev/null || echo 2)}
case "$WORKERS" in 1|2|3|4) ;; *) echo "! invalid workers '$WORKERS' — using 2"; WORKERS=2;; esac
export WORKERS
COMPOSE_FILES=(-f compose.yml)
if [ -n "${MF_COMPOSE_OVERRIDE:-}" ]; then
  [ -f "$MF_COMPOSE_OVERRIDE" ] || {
    echo "✗ MF_COMPOSE_OVERRIDE must name one existing Compose file"
    exit 1
  }
  OVERRIDE_DIR=$(cd "$(dirname "$MF_COMPOSE_OVERRIDE")" && pwd -P)
  OVERRIDE_FILE="$OVERRIDE_DIR/$(basename "$MF_COMPOSE_OVERRIDE")"
  COMPOSE_FILES+=(-f "$OVERRIDE_FILE")
fi
if [ "$WORKERS" -gt 2 ]; then
  {
    echo "# GENERATED by autorun.sh for WORKERS=$WORKERS — do not edit, not committed."
    echo "services:"
    w=3
    while [ "$w" -le "$WORKERS" ]; do
      cat <<EXTRA
  worker-$w:
    build: ../factory
    env_file: ../factory/.env
    restart: unless-stopped
    entrypoint: ['bash', '/work/mf/worker.sh']
    environment:
      FACTORY_NAME: multi
      WORKERS: \${WORKERS:-2}
      MF_DRY_RUN: \${MF_DRY_RUN:-0}
      MF_MODELS_FILE: \${MF_MODELS_FILE:-/work/mfstate/control/models.json}
      CCR_HOME: /home/factory/.claude-code-router
      WORKER_ID: '$w'
    volumes:
      - mf-w$w-work:/work/state
      - ./state:/work/mfstate
      - ./worker.sh:/work/mf/worker.sh:ro
      - ./mflib.sh:/work/mf/mflib.sh:ro
      - ./contracts.sh:/work/mf/contracts.sh:ro
      - ./create-issue.sh:/work/mf/create-issue.sh:ro
      - ./ccr-common.mjs:/work/mf/ccr-common.mjs:ro
      - ./ccr-bootstrap.mjs:/work/mf/ccr-bootstrap.mjs:ro
      - ./ccr-ensure.mjs:/work/mf/ccr-ensure.mjs:ro
      - ./claudex-direct-probe.mjs:/work/mf/claudex-direct-probe.mjs:ro
      - ./provider-test.sh:/work/mf/provider-test.sh:ro
      - ../factory/lib.sh:/work/mf/lib.sh:ro
      - ../factory/prompts:/work/state/prompts:ro
      - ./prompts:/work/state/mf-prompts:ro
      - ../factory/usage:/work/usage
      - ./auth/worker-$w/codex:/home/factory/.codex
      - ./auth/worker-$w/ccr:/home/factory/.claude-code-router
      - ./auth/worker-$w/gemini:/home/factory/.gemini
EXTRA
      w=$((w+1))
    done
    echo "volumes:"
    w=3
    while [ "$w" -le "$WORKERS" ]; do echo "  mf-w$w-work:"; w=$((w+1)); done
  } > compose.extra.yml
  COMPOSE_FILES+=(-f compose.extra.yml)
fi
dc(){ $DOCKER compose "${COMPOSE_FILES[@]}" "$@"; }
# Project-scoped compose retains the selected override for every lifecycle path.
dcp(){ $DOCKER compose "${COMPOSE_FILES[@]}" -p bettertrack-multifactory "$@"; }

require_env(){
  [ -f ../factory/.env ] || { echo "✗ factory/.env missing. Copy .env.example → .env and fill the tokens."; exit 1; }
}

# docker ps lists running AND paused containers, so a paused single factory blocks too.
guard_single_factory(){
  if [ -n "$($DOCKER ps -q --filter label=com.docker.compose.project=bettertrack-factory)" ]; then
    echo "✗ The single factory (bettertrack-factory) is running/paused."
    echo "  The two factories must never run at the same time against the repo."
    echo "  Stop it first:  ./factory/autorun.sh --stop"
    exit 1
  fi
}

# Copy provider CLI credentials from the host into gitignored PER-CONTAINER dirs
# (multi-factory/auth/<service>/…) that compose bind-mounts over the container
# HOME. Per-container copies keep token-refresh writes from racing across
# containers; a copy is only overwritten when the host file is NEWER (so a
# container-refreshed token survives restarts while a fresh host login wins).
# Missing host auth is a warning, not an error — that provider simply reports
# unavailable until the owner logs in on the host and restarts.
sync_file(){ # $1=src $2=dst
  [ -f "$1" ] || return 0
  if [ ! -f "$2" ] || [ "$1" -nt "$2" ]; then cp -f "$1" "$2" && chmod 600 "$2"; fi
}
# The Antigravity (agy) OAuth token: a plain file on Linux hosts, but the macOS
# keychain ("Antigravity Safe Storage") on a Mac — where no copyable file exists.
# So the container gemini credential comes from a ONE-TIME in-container login
# (./autorun.sh --login-gemini) that writes the token into auth/<primary>/gemini,
# which this function then fans out to every other container. GEMINI_PRIMARY is
# the dir the login writes to.
GEMINI_PRIMARY=master
AGY_TOKEN_REL=antigravity-cli/antigravity-oauth-token
gemini_container_authed(){ [ -s "auth/$GEMINI_PRIMARY/gemini/$AGY_TOKEN_REL" ]; }

sync_provider_auth(){
  local services="master" w c
  for w in $(seq 1 "$WORKERS"); do services="$services worker-$w"; done
  for c in $services; do
    mkdir -p "auth/$c/codex" "auth/$c/ccr" \
      "auth/$c/gemini/antigravity-cli" "auth/$c/gemini/config"
    chmod 700 "auth/$c/codex" "auth/$c/ccr" "auth/$c/gemini" 2>/dev/null || true
    # codex (ChatGPT subscription): auth.json is the credential; config.toml is
    # GENERATED for the container (trust the factory clone), never copied.
    sync_file "$HOME/.codex/auth.json" "auth/$c/codex/auth.json"
    sync_file "$HOME/.codex/models_cache.json" "auth/$c/codex/models_cache.json"
    printf '[projects."/work/state/repo"]\ntrust_level = "trusted"\n' > "auth/$c/codex/config.toml"
    chmod 600 "auth/$c/codex/config.toml"
    # ClaudeX has one private, writable CCR home per service. It imports from
    # that service's Codex copy at runtime; host CCR databases are never copied.
    # antigravity/gemini (Google subscription): account/install ids + generated
    # trust/settings; the actual OAuth TOKEN comes from --login-gemini (below).
    sync_file "$HOME/.gemini/google_accounts.json" "auth/$c/gemini/google_accounts.json"
    sync_file "$HOME/.gemini/installation_id"      "auth/$c/gemini/installation_id"
    sync_file "$HOME/.gemini/antigravity-cli/installation_id" "auth/$c/gemini/antigravity-cli/installation_id"
    # Linux hosts keep the token in a plain file — copy it straight through.
    sync_file "$HOME/.gemini/$AGY_TOKEN_REL" "auth/$c/gemini/$AGY_TOKEN_REL"
    printf '{\n  "security": { "auth": { "selectedType": "oauth-personal" } }\n}\n' > "auth/$c/gemini/settings.json"
    printf '{\n  "/work/state/repo": "TRUST_FOLDER"\n}\n' > "auth/$c/gemini/trustedFolders.json"
    printf '{\n  "enableTelemetry": false,\n  "trustedWorkspaces": ["/work/state/repo"]\n}\n' > "auth/$c/gemini/antigravity-cli/settings.json"
  done
  # Fan the in-container login token out from the primary to every other container.
  if gemini_container_authed; then
    for c in $services; do
      [ "$c" = "$GEMINI_PRIMARY" ] && continue
      sync_file "auth/$GEMINI_PRIMARY/gemini/$AGY_TOKEN_REL" "auth/$c/gemini/$AGY_TOKEN_REL"
    done
  fi
  chmod -R go-rwx auth 2>/dev/null || true
  [ -f "$HOME/.codex/auth.json" ] || echo "! codex auth not found (~/.codex/auth.json) — codex provider unavailable until 'codex login' on the host"
  if [ ! -f "$HOME/.gemini/$AGY_TOKEN_REL" ] && ! gemini_container_authed; then
    echo "! antigravity/gemini not authorized for the containers yet."
    echo "  On macOS the agy token lives in the keychain and can't be copied — run ONE-TIME:"
    echo "    ./multi-factory/autorun.sh --login-gemini"
  fi
}

# One-time interactive Antigravity login INSIDE a container: agy writes its OAuth
# token into the bind-mounted auth/master/gemini, which sync_provider_auth then
# fans out to the workers. Owner runs this once; the token persists on the host.
login_gemini(){
  require_env
  echo "→ building image (ensures agy is present)…"; dc build master >/dev/null
  mkdir -p "auth/$GEMINI_PRIMARY/gemini/antigravity-cli"
  printf '{\n  "enableTelemetry": false,\n  "trustedWorkspaces": ["/work/state/repo"]\n}\n' \
    > "auth/$GEMINI_PRIMARY/gemini/antigravity-cli/settings.json"
  echo "→ launching interactive 'agy' login (complete the Google sign-in, then /quit)…"
  $DOCKER run --rm -it \
    -v "$PWD/auth/$GEMINI_PRIMARY/gemini:/home/factory/.gemini" \
    --entrypoint agy "$(dc config --images master | head -1)" || true
  if gemini_container_authed; then
    echo "✓ antigravity token captured — it will sync to all workers on the next start."
  else
    echo "✗ no token was written. Re-run and finish the sign-in, or check 'agy' login output."
  fi
}

prepare_state(){
  mkdir -p state/assignments state/status state/merge-queue state/control state/logs prompts
  rm -f state/STOP state/control/dry-done
  sync_provider_auth
  # Drop protocol files of workers beyond the configured count so the master
  # never assigns to a container that will not start.
  for f in state/assignments/worker-*.json state/status/worker-*.json state/status/worker-*.hb; do
    [ -e "$f" ] || continue
    id=$(basename "$f" | sed 's/worker-\([0-9]*\).*/\1/')
    [ -n "$id" ] && [ "$id" -gt "$WORKERS" ] && rm -f "$f"
  done
  # (Re)starting the factory means: run. Drain modes are set via control/mode later.
  printf 'run\n' > state/control/mode.tmp && mv -f state/control/mode.tmp state/control/mode
}

case "${1:-up}" in
  --logs)  dcp logs -f; exit $? ;;
  --login-gemini) login_gemini; exit 0 ;;
  --stop)  echo "→ stopping multi-factory"; dcp stop; echo "✓ stopped. Resume with: ./multi-factory/autorun.sh"; exit 0 ;;
  --down)  echo "→ downing multi-factory"; dcp down --remove-orphans; echo "✓ removed (state/ and clone volumes kept)"; exit 0 ;;
  --fresh) require_env; guard_single_factory
           echo "→ wiping multi-factory state + clone volumes"
           dc down -v --remove-orphans 2>/dev/null || true
           rm -rf state; prepare_state ;;
  --dry)   require_env; guard_single_factory; prepare_state
           echo "→ building image…"; dc build
           echo "→ starting multi-factory in DRY-RUN mode (no LLM calls)…"
           MF_DRY_RUN=1 dc up -d --force-recreate
           dc ps; exit 0 ;;
  up|"")   require_env; guard_single_factory; prepare_state ;;
  *) echo "usage: autorun.sh [--dry|--logs|--stop|--down|--fresh|--login-gemini]"; exit 1 ;;
esac

echo "→ building image…"
dc build
echo "→ starting multi-factory (detached, restart=unless-stopped, workers=$WORKERS)…"
if [ "$WORKERS" = 1 ]; then
  MF_DRY_RUN=${MF_DRY_RUN:-0} dc up -d --force-recreate --remove-orphans master worker-1
else
  MF_DRY_RUN=${MF_DRY_RUN:-0} dc up -d --force-recreate --remove-orphans
fi
sleep 2
dc ps
cat <<'EOF'

✓ Multi-factory running: 1 master (composer → scheduler → merger) + workers.

  Dashboard:  node multi-factory/control/server.mjs   →  http://127.0.0.1:8790
  Watch:      ./multi-factory/autorun.sh --logs
  Stop:       ./multi-factory/autorun.sh --stop        (hard, resumable)
  Drain:      echo run-out    > multi-factory/state/control/mode   (finish ALL open issues, then idle)
              echo close-down > multi-factory/state/control/mode   (finish in-flight only, then idle)
  Pause:      docker compose -p bettertrack-multifactory pause / unpause
EOF
