#!/usr/bin/env bash
# BetterTrack Multi-Factory — Autorun launcher (run on the HOST).
#
#   ./multi-factory/autorun.sh            # build + start master and N workers, detached
#   ./multi-factory/autorun.sh --dry      # start in MF_DRY_RUN=1 mode (no LLM calls)
#   ./multi-factory/autorun.sh --logs     # follow all container logs
#   ./multi-factory/autorun.sh --stop     # stop containers (resume later with autorun.sh)
#   ./multi-factory/autorun.sh --down     # stop AND remove containers (state/ dir persists)
#   ./multi-factory/autorun.sh --fresh    # wipe protocol state + clone volumes, start clean
#
# The single factory and the multi-factory must NEVER run at the same time against
# the repo — both launchers refuse to start while the other project has containers.
# Prefer the control dashboard (multi-factory/control/) for day-to-day start/stop/
# pause/run-out/close-down.
set -euo pipefail
cd "$(dirname "$0")"

if docker info >/dev/null 2>&1; then DOCKER=docker; else DOCKER="sudo docker"; fi

# Worker count: env override > state/control/workers (dashboard-set) > 2.
# 2 is the sweet spot (api + web lanes); >2 pays only with more open lanes; hard cap 4.
WORKERS=${WORKERS:-$(cat state/control/workers 2>/dev/null || echo 2)}
case "$WORKERS" in 1|2|3|4) ;; *) echo "! invalid workers '$WORKERS' — using 2"; WORKERS=2;; esac
export WORKERS
COMPOSE_FILES="-f compose.yml"
if [ "$WORKERS" -gt 2 ]; then
  {
    echo "# GENERATED by autorun.sh for WORKERS=$WORKERS — do not edit, not committed."
    echo "services:"
    w=3
    while [ "$w" -le "$WORKERS" ]; do
      cat <<EXTRA
  worker-$w:
    build: ../factory
    env_file: ../factory/.env
    restart: unless-stopped
    entrypoint: ['bash', '/work/mf/worker.sh']
    environment:
      FACTORY_NAME: multi
      WORKERS: \${WORKERS:-2}
      MF_DRY_RUN: \${MF_DRY_RUN:-0}
      WORKER_ID: '$w'
    volumes:
      - mf-w$w-work:/work/state
      - ./state:/work/mfstate
      - ./worker.sh:/work/mf/worker.sh:ro
      - ../factory/lib.sh:/work/mf/lib.sh:ro
      - ../factory/prompts:/work/state/prompts:ro
      - ./prompts:/work/state/mf-prompts:ro
      - ../factory/usage:/work/usage
EXTRA
      w=$((w+1))
    done
    echo "volumes:"
    w=3
    while [ "$w" -le "$WORKERS" ]; do echo "  mf-w$w-work:"; w=$((w+1)); done
  } > compose.extra.yml
  COMPOSE_FILES="$COMPOSE_FILES -f compose.extra.yml"
fi
dc(){ $DOCKER compose $COMPOSE_FILES "$@"; }
# Project-scoped compose (finds ALL containers incl. extra workers regardless of files)
dcp(){ $DOCKER compose -p bettertrack-multifactory "$@"; }

require_env(){
  [ -f ../factory/.env ] || { echo "✗ factory/.env missing. Copy .env.example → .env and fill the tokens."; exit 1; }
}

# docker ps lists running AND paused containers, so a paused single factory blocks too.
guard_single_factory(){
  if [ -n "$($DOCKER ps -q --filter label=com.docker.compose.project=bettertrack-factory)" ]; then
    echo "✗ The single factory (bettertrack-factory) is running/paused."
    echo "  The two factories must never run at the same time against the repo."
    echo "  Stop it first:  ./factory/autorun.sh --stop"
    exit 1
  fi
}

prepare_state(){
  mkdir -p state/assignments state/status state/merge-queue state/control state/logs prompts
  rm -f state/STOP state/control/dry-done
  # Drop protocol files of workers beyond the configured count so the master
  # never assigns to a container that will not start.
  for f in state/assignments/worker-*.json state/status/worker-*.json state/status/worker-*.hb; do
    [ -e "$f" ] || continue
    id=$(basename "$f" | sed 's/worker-\([0-9]*\).*/\1/')
    [ -n "$id" ] && [ "$id" -gt "$WORKERS" ] && rm -f "$f"
  done
  # (Re)starting the factory means: run. Drain modes are set via control/mode later.
  printf 'run\n' > state/control/mode.tmp && mv -f state/control/mode.tmp state/control/mode
}

case "${1:-up}" in
  --logs)  exec dcp logs -f ;;
  --stop)  echo "→ stopping multi-factory"; dcp stop; echo "✓ stopped. Resume with: ./multi-factory/autorun.sh"; exit 0 ;;
  --down)  echo "→ downing multi-factory"; dcp down --remove-orphans; echo "✓ removed (state/ and clone volumes kept)"; exit 0 ;;
  --fresh) require_env; guard_single_factory
           echo "→ wiping multi-factory state + clone volumes"
           dc down -v --remove-orphans 2>/dev/null || true
           rm -rf state; prepare_state ;;
  --dry)   require_env; guard_single_factory; prepare_state
           echo "→ building image…"; dc build
           echo "→ starting multi-factory in DRY-RUN mode (no LLM calls)…"
           MF_DRY_RUN=1 dc up -d --force-recreate
           dc ps; exit 0 ;;
  up|"")   require_env; guard_single_factory; prepare_state ;;
  *) echo "usage: autorun.sh [--dry|--logs|--stop|--down|--fresh]"; exit 1 ;;
esac

echo "→ building image…"
dc build
echo "→ starting multi-factory (detached, restart=unless-stopped, workers=$WORKERS)…"
if [ "$WORKERS" = 1 ]; then
  MF_DRY_RUN=${MF_DRY_RUN:-0} dc up -d --force-recreate --remove-orphans master worker-1
else
  MF_DRY_RUN=${MF_DRY_RUN:-0} dc up -d --force-recreate --remove-orphans
fi
sleep 2
dc ps
cat <<'EOF'

✓ Multi-factory running: 1 master (composer → scheduler → merger) + workers.

  Dashboard:  node multi-factory/control/server.mjs   →  http://127.0.0.1:8790
  Watch:      ./multi-factory/autorun.sh --logs
  Stop:       ./multi-factory/autorun.sh --stop        (hard, resumable)
  Drain:      echo run-out    > multi-factory/state/control/mode   (finish ALL open issues, then idle)
              echo close-down > multi-factory/state/control/mode   (finish in-flight only, then idle)
  Pause:      docker compose -p bettertrack-multifactory pause / unpause
EOF
