import type { GlobalAssetUpsert } from '../../data/repositories/assetRepository';

/**
 * The shipped common-symbols catalog content (PROJECTPLAN.md §6.2(c)): major
 * global indices, the world/EM UCITS ETFs EU retail investors actually buy plus
 * flagship US ETFs, the DAX 40 / ATX 20 / S&P 500 constituents, the top cryptos
 * by market cap, major FX pairs and key commodities. Every row carries its real
 * Yahoo `providerRef`, native currency, exchange and asset type so the local
 * search catalog answers instantly without a provider round-trip.
 *
 * This is pure data — the idempotent upsert plumbing and the "no history
 * backfill at seed" guarantee live in {@link ./catalogSeed}. Rows here never
 * enqueue jobs; a seeded asset's history is only backfilled the first time a
 * user references it (workboard add / transaction).
 */
type Entry = GlobalAssetUpsert;

const YAHOO = 'yahoo';

function entry(
  type: Entry['type'],
  ref: string,
  name: string,
  exchange: string | null,
  currency: string,
): Entry {
  return { providerId: YAHOO, providerRef: ref, type, symbol: ref, name, exchange, currency };
}

/** Map `[ref, name, exchange]` tuples to US-listed common stocks (USD). */
function usStocks(rows: readonly (readonly [string, string, string])[]): Entry[] {
  return rows.map(([ref, name, ex]) => entry('stock', ref, name, ex, 'USD'));
}

/** Map `[ref, name]` tuples to stocks on a single exchange/currency. */
function stocksOn(
  exchange: string,
  currency: string,
  rows: readonly (readonly [string, string])[],
): Entry[] {
  return rows.map(([ref, name]) => entry('stock', ref, name, exchange, currency));
}

// ── Major global indices ─────────────────────────────────────────────────────
const INDICES: Entry[] = [
  entry('index', '^GSPC', 'S&P 500 Index', 'SNP', 'USD'),
  entry('index', '^DJI', 'Dow Jones Industrial Average', 'DJI', 'USD'),
  entry('index', '^IXIC', 'NASDAQ Composite Index', 'NASDAQ', 'USD'),
  entry('index', '^NDX', 'NASDAQ 100 Index', 'NASDAQ', 'USD'),
  entry('index', '^GDAXI', 'DAX Performance Index', 'XETRA', 'EUR'),
  entry('index', '^ATX', 'Austrian Traded Index (ATX)', 'VIE', 'EUR'),
  entry('index', '^STOXX50E', 'EURO STOXX 50 Index', 'STOXX', 'EUR'),
  entry('index', '^FTSE', 'FTSE 100 Index', 'FTSE', 'GBP'),
  entry('index', '^N225', 'Nikkei 225 Index', 'OSA', 'JPY'),
  entry('index', '^FCHI', 'CAC 40 Index', 'PAR', 'EUR'),
  entry('index', '^HSI', 'Hang Seng Index', 'HKG', 'HKD'),
];

// ── Broad index ETFs (§6.2(c): MSCI World / ACWI / EM + flagship US ETFs) ─────
// MSCI World / ACWI / EM index exposure ships via the UCITS ETFs EU retail
// investors actually hold (names carry "MSCI World/ACWI/EM" so those searches
// resolve locally) plus the flagship US-listed ETFs.
const ETFS: Entry[] = [
  // MSCI World
  entry('etf', 'EUNL.DE', 'iShares Core MSCI World UCITS ETF USD (Acc)', 'XETRA', 'EUR'),
  entry('etf', 'IWDA.L', 'iShares Core MSCI World UCITS ETF USD (Acc)', 'LSE', 'USD'),
  entry('etf', 'XDWD.DE', 'Xtrackers MSCI World UCITS ETF 1C', 'XETRA', 'EUR'),
  entry('etf', 'URTH', 'iShares MSCI World ETF', 'NYSE', 'USD'),
  // MSCI ACWI / FTSE All-World
  entry('etf', 'SSAC.L', 'iShares MSCI ACWI UCITS ETF USD (Acc)', 'LSE', 'USD'),
  entry('etf', 'ACWI', 'iShares MSCI ACWI ETF', 'NASDAQ', 'USD'),
  entry('etf', 'VWCE.DE', 'Vanguard FTSE All-World UCITS ETF USD Acc', 'XETRA', 'EUR'),
  entry('etf', 'VWRL.L', 'Vanguard FTSE All-World UCITS ETF USD Dis', 'LSE', 'USD'),
  // MSCI Emerging Markets
  entry('etf', 'IS3N.DE', 'iShares Core MSCI EM IMI UCITS ETF USD (Acc)', 'XETRA', 'EUR'),
  entry('etf', 'EIMI.L', 'iShares Core MSCI EM IMI UCITS ETF USD (Acc)', 'LSE', 'USD'),
  entry('etf', 'VFEM.L', 'Vanguard FTSE Emerging Markets UCITS ETF', 'LSE', 'USD'),
  entry('etf', 'EEM', 'iShares MSCI Emerging Markets ETF', 'NYSE', 'USD'),
  // S&P 500 (EU UCITS + flagship US)
  entry('etf', 'SXR8.DE', 'iShares Core S&P 500 UCITS ETF USD (Acc)', 'XETRA', 'EUR'),
  entry('etf', 'CSPX.L', 'iShares Core S&P 500 UCITS ETF USD (Acc)', 'LSE', 'USD'),
  entry('etf', 'VUAA.DE', 'Vanguard S&P 500 UCITS ETF USD Acc', 'XETRA', 'EUR'),
  entry('etf', 'VUSA.L', 'Vanguard S&P 500 UCITS ETF USD Dis', 'LSE', 'USD'),
  entry('etf', 'SPY', 'SPDR S&P 500 ETF Trust', 'NYSE', 'USD'),
  entry('etf', 'VOO', 'Vanguard S&P 500 ETF', 'NYSE', 'USD'),
  entry('etf', 'IVV', 'iShares Core S&P 500 ETF', 'NYSE', 'USD'),
  // Nasdaq / total market
  entry('etf', 'QQQ', 'Invesco QQQ Trust', 'NASDAQ', 'USD'),
  entry('etf', 'VTI', 'Vanguard Total Stock Market ETF', 'NYSE', 'USD'),
];

// ── DAX 40 constituents (XETRA, EUR) ─────────────────────────────────────────
const DAX40: Entry[] = stocksOn('XETRA', 'EUR', [
  ['ADS.DE', 'adidas AG'],
  ['AIR.DE', 'Airbus SE'],
  ['ALV.DE', 'Allianz SE'],
  ['BAS.DE', 'BASF SE'],
  ['BAYN.DE', 'Bayer AG'],
  ['BEI.DE', 'Beiersdorf AG'],
  ['BMW.DE', 'Bayerische Motoren Werke AG (BMW)'],
  ['BNR.DE', 'Brenntag SE'],
  ['CBK.DE', 'Commerzbank AG'],
  ['CON.DE', 'Continental AG'],
  ['1COV.DE', 'Covestro AG'],
  ['DTG.DE', 'Daimler Truck Holding AG'],
  ['DHL.DE', 'DHL Group (Deutsche Post AG)'],
  ['DBK.DE', 'Deutsche Bank AG'],
  ['DB1.DE', 'Deutsche Börse AG'],
  ['DTE.DE', 'Deutsche Telekom AG'],
  ['EOAN.DE', 'E.ON SE'],
  ['FRE.DE', 'Fresenius SE & Co. KGaA'],
  ['HNR1.DE', 'Hannover Rück SE'],
  ['HEI.DE', 'Heidelberg Materials AG'],
  ['HEN3.DE', 'Henkel AG & Co. KGaA (Pref)'],
  ['IFX.DE', 'Infineon Technologies AG'],
  ['MBG.DE', 'Mercedes-Benz Group AG'],
  ['MRK.DE', 'Merck KGaA'],
  ['MTX.DE', 'MTU Aero Engines AG'],
  ['MUV2.DE', 'Münchener Rück AG (Munich Re)'],
  ['P911.DE', 'Dr. Ing. h.c. F. Porsche AG'],
  ['PAH3.DE', 'Porsche Automobil Holding SE'],
  ['QIA.DE', 'Qiagen N.V.'],
  ['RHM.DE', 'Rheinmetall AG'],
  ['RWE.DE', 'RWE AG'],
  ['SAP.DE', 'SAP SE'],
  ['SRT3.DE', 'Sartorius AG (Pref)'],
  ['SIE.DE', 'Siemens AG'],
  ['ENR.DE', 'Siemens Energy AG'],
  ['SHL.DE', 'Siemens Healthineers AG'],
  ['SY1.DE', 'Symrise AG'],
  ['VOW3.DE', 'Volkswagen AG (Pref)'],
  ['VNA.DE', 'Vonovia SE'],
  ['ZAL.DE', 'Zalando SE'],
]);

// ── ATX 20 constituents (Vienna, EUR) ────────────────────────────────────────
const ATX20: Entry[] = stocksOn('VIE', 'EUR', [
  ['ANDR.VI', 'Andritz AG'],
  ['ATS.VI', 'AT&S Austria Technologie & Systemtechnik AG'],
  ['BG.VI', 'BAWAG Group AG'],
  ['CAI.VI', 'CA Immobilien Anlagen AG'],
  ['CPI.VI', 'CPI Europe AG'],
  ['DOC.VI', 'DO & CO AG'],
  ['EBS.VI', 'Erste Group Bank AG'],
  ['EVN.VI', 'EVN AG'],
  ['LNZ.VI', 'Lenzing AG'],
  ['MMK.VI', 'Mayr-Melnhof Karton AG'],
  ['OMV.VI', 'OMV AG'],
  ['POST.VI', 'Österreichische Post AG'],
  ['RBI.VI', 'Raiffeisen Bank International AG'],
  ['SBO.VI', 'Schoeller-Bleckmann Oilfield Equipment AG'],
  ['TKA.VI', 'Telekom Austria AG'],
  ['UQA.VI', 'UNIQA Insurance Group AG'],
  ['VER.VI', 'Verbund AG'],
  ['VIG.VI', 'Vienna Insurance Group AG'],
  ['VOE.VI', 'voestalpine AG'],
  ['WIE.VI', 'Wienerberger AG'],
]);

// ── S&P 500 constituents (US-listed, USD) ────────────────────────────────────
const SP500: Entry[] = usStocks([
  ['AAPL', 'Apple Inc.', 'NASDAQ'],
  ['MSFT', 'Microsoft Corporation', 'NASDAQ'],
  ['NVDA', 'NVIDIA Corporation', 'NASDAQ'],
  ['AMZN', 'Amazon.com, Inc.', 'NASDAQ'],
  ['GOOGL', 'Alphabet Inc. (Class A)', 'NASDAQ'],
  ['GOOG', 'Alphabet Inc. (Class C)', 'NASDAQ'],
  ['META', 'Meta Platforms, Inc.', 'NASDAQ'],
  ['BRK-B', 'Berkshire Hathaway Inc. (Class B)', 'NYSE'],
  ['AVGO', 'Broadcom Inc.', 'NASDAQ'],
  ['TSLA', 'Tesla, Inc.', 'NASDAQ'],
  ['LLY', 'Eli Lilly and Company', 'NYSE'],
  ['JPM', 'JPMorgan Chase & Co.', 'NYSE'],
  ['V', 'Visa Inc.', 'NYSE'],
  ['XOM', 'Exxon Mobil Corporation', 'NYSE'],
  ['UNH', 'UnitedHealth Group Incorporated', 'NYSE'],
  ['MA', 'Mastercard Incorporated', 'NYSE'],
  ['COST', 'Costco Wholesale Corporation', 'NASDAQ'],
  ['JNJ', 'Johnson & Johnson', 'NYSE'],
  ['HD', 'The Home Depot, Inc.', 'NYSE'],
  ['PG', 'The Procter & Gamble Company', 'NYSE'],
  ['WMT', 'Walmart Inc.', 'NYSE'],
  ['NFLX', 'Netflix, Inc.', 'NASDAQ'],
  ['ABBV', 'AbbVie Inc.', 'NYSE'],
  ['BAC', 'Bank of America Corporation', 'NYSE'],
  ['CRM', 'Salesforce, Inc.', 'NYSE'],
  ['ORCL', 'Oracle Corporation', 'NYSE'],
  ['CVX', 'Chevron Corporation', 'NYSE'],
  ['KO', 'The Coca-Cola Company', 'NYSE'],
  ['MRK', 'Merck & Co., Inc.', 'NYSE'],
  ['AMD', 'Advanced Micro Devices, Inc.', 'NASDAQ'],
  ['PEP', 'PepsiCo, Inc.', 'NASDAQ'],
  ['TMO', 'Thermo Fisher Scientific Inc.', 'NYSE'],
  ['LIN', 'Linde plc', 'NASDAQ'],
  ['ACN', 'Accenture plc', 'NYSE'],
  ['CSCO', 'Cisco Systems, Inc.', 'NASDAQ'],
  ['ADBE', 'Adobe Inc.', 'NASDAQ'],
  ['MCD', "McDonald's Corporation", 'NYSE'],
  ['WFC', 'Wells Fargo & Company', 'NYSE'],
  ['ABT', 'Abbott Laboratories', 'NYSE'],
  ['GE', 'GE Aerospace', 'NYSE'],
  ['DHR', 'Danaher Corporation', 'NYSE'],
  ['TXN', 'Texas Instruments Incorporated', 'NASDAQ'],
  ['NOW', 'ServiceNow, Inc.', 'NYSE'],
  ['CAT', 'Caterpillar Inc.', 'NYSE'],
  ['IBM', 'International Business Machines Corporation', 'NYSE'],
  ['QCOM', 'QUALCOMM Incorporated', 'NASDAQ'],
  ['INTU', 'Intuit Inc.', 'NASDAQ'],
  ['VZ', 'Verizon Communications Inc.', 'NYSE'],
  ['AMGN', 'Amgen Inc.', 'NASDAQ'],
  ['CMCSA', 'Comcast Corporation', 'NASDAQ'],
  ['PM', 'Philip Morris International Inc.', 'NYSE'],
  ['ISRG', 'Intuitive Surgical, Inc.', 'NASDAQ'],
  ['SPGI', 'S&P Global Inc.', 'NYSE'],
  ['UNP', 'Union Pacific Corporation', 'NYSE'],
  ['GS', 'The Goldman Sachs Group, Inc.', 'NYSE'],
  ['RTX', 'RTX Corporation', 'NYSE'],
  ['NKE', 'NIKE, Inc.', 'NYSE'],
  ['HON', 'Honeywell International Inc.', 'NASDAQ'],
  ['T', 'AT&T Inc.', 'NYSE'],
  ['PFE', 'Pfizer Inc.', 'NYSE'],
  ['LOW', "Lowe's Companies, Inc.", 'NYSE'],
  ['AXP', 'American Express Company', 'NYSE'],
  ['ELV', 'Elevance Health, Inc.', 'NYSE'],
  ['BKNG', 'Booking Holdings Inc.', 'NASDAQ'],
  ['SYK', 'Stryker Corporation', 'NYSE'],
  ['BLK', 'BlackRock, Inc.', 'NYSE'],
  ['C', 'Citigroup Inc.', 'NYSE'],
  ['TJX', 'The TJX Companies, Inc.', 'NYSE'],
  ['SCHW', 'The Charles Schwab Corporation', 'NYSE'],
  ['MDT', 'Medtronic plc', 'NYSE'],
  ['ADP', 'Automatic Data Processing, Inc.', 'NASDAQ'],
  ['VRTX', 'Vertex Pharmaceuticals Incorporated', 'NASDAQ'],
  ['BSX', 'Boston Scientific Corporation', 'NYSE'],
  ['DE', 'Deere & Company', 'NYSE'],
  ['MMC', 'Marsh & McLennan Companies, Inc.', 'NYSE'],
  ['PLD', 'Prologis, Inc.', 'NYSE'],
  ['CB', 'Chubb Limited', 'NYSE'],
  ['LMT', 'Lockheed Martin Corporation', 'NYSE'],
  ['REGN', 'Regeneron Pharmaceuticals, Inc.', 'NASDAQ'],
  ['ADI', 'Analog Devices, Inc.', 'NASDAQ'],
  ['GILD', 'Gilead Sciences, Inc.', 'NASDAQ'],
  ['MO', 'Altria Group, Inc.', 'NYSE'],
  ['AMT', 'American Tower Corporation', 'NYSE'],
  ['CI', 'The Cigna Group', 'NYSE'],
  ['BMY', 'Bristol-Myers Squibb Company', 'NYSE'],
  ['MU', 'Micron Technology, Inc.', 'NASDAQ'],
  ['FI', 'Fiserv, Inc.', 'NYSE'],
  ['SO', 'The Southern Company', 'NYSE'],
  ['PGR', 'The Progressive Corporation', 'NYSE'],
  ['ETN', 'Eaton Corporation plc', 'NYSE'],
  ['DUK', 'Duke Energy Corporation', 'NYSE'],
  ['SBUX', 'Starbucks Corporation', 'NASDAQ'],
  ['ZTS', 'Zoetis Inc.', 'NYSE'],
  ['CVS', 'CVS Health Corporation', 'NYSE'],
  ['MELI', 'MercadoLibre, Inc.', 'NASDAQ'],
  ['CL', 'Colgate-Palmolive Company', 'NYSE'],
  ['ITW', 'Illinois Tool Works Inc.', 'NYSE'],
  ['BDX', 'Becton, Dickinson and Company', 'NYSE'],
  ['EQIX', 'Equinix, Inc.', 'NASDAQ'],
  ['APH', 'Amphenol Corporation', 'NYSE'],
  ['WM', 'Waste Management, Inc.', 'NYSE'],
  ['CME', 'CME Group Inc.', 'NASDAQ'],
  ['NOC', 'Northrop Grumman Corporation', 'NYSE'],
  ['TDG', 'TransDigm Group Incorporated', 'NYSE'],
  ['CSX', 'CSX Corporation', 'NASDAQ'],
  ['MCK', 'McKesson Corporation', 'NYSE'],
  ['ICE', 'Intercontinental Exchange, Inc.', 'NYSE'],
  ['USB', 'U.S. Bancorp', 'NYSE'],
  ['PNC', 'The PNC Financial Services Group, Inc.', 'NYSE'],
  ['AON', 'Aon plc', 'NYSE'],
  ['FCX', 'Freeport-McMoRan Inc.', 'NYSE'],
  ['GD', 'General Dynamics Corporation', 'NYSE'],
  ['EMR', 'Emerson Electric Co.', 'NYSE'],
  ['MMM', '3M Company', 'NYSE'],
  ['ORLY', "O'Reilly Automotive, Inc.", 'NASDAQ'],
  ['CTAS', 'Cintas Corporation', 'NASDAQ'],
  ['MAR', 'Marriott International, Inc.', 'NASDAQ'],
  ['APD', 'Air Products and Chemicals, Inc.', 'NYSE'],
  ['CARR', 'Carrier Global Corporation', 'NYSE'],
  ['GM', 'General Motors Company', 'NYSE'],
  ['FDX', 'FedEx Corporation', 'NYSE'],
  ['HCA', 'HCA Healthcare, Inc.', 'NYSE'],
  ['NXPI', 'NXP Semiconductors N.V.', 'NASDAQ'],
  ['ROP', 'Roper Technologies, Inc.', 'NASDAQ'],
  ['SLB', 'Schlumberger Limited (SLB)', 'NYSE'],
  ['PYPL', 'PayPal Holdings, Inc.', 'NASDAQ'],
  ['PSX', 'Phillips 66', 'NYSE'],
  ['AJG', 'Arthur J. Gallagher & Co.', 'NYSE'],
  ['MPC', 'Marathon Petroleum Corporation', 'NYSE'],
  ['NSC', 'Norfolk Southern Corporation', 'NYSE'],
  ['TT', 'Trane Technologies plc', 'NYSE'],
  ['ECL', 'Ecolab Inc.', 'NYSE'],
  ['WELL', 'Welltower Inc.', 'NYSE'],
  ['AZO', 'AutoZone, Inc.', 'NYSE'],
  ['PH', 'Parker-Hannifin Corporation', 'NYSE'],
  ['CPRT', 'Copart, Inc.', 'NASDAQ'],
  ['ADSK', 'Autodesk, Inc.', 'NASDAQ'],
  ['MSI', 'Motorola Solutions, Inc.', 'NYSE'],
  ['DLR', 'Digital Realty Trust, Inc.', 'NYSE'],
  ['SPG', 'Simon Property Group, Inc.', 'NYSE'],
  ['O', 'Realty Income Corporation', 'NYSE'],
  ['CMG', 'Chipotle Mexican Grill, Inc.', 'NYSE'],
  ['ROST', 'Ross Stores, Inc.', 'NASDAQ'],
  ['AFL', 'Aflac Incorporated', 'NYSE'],
  ['TFC', 'Truist Financial Corporation', 'NYSE'],
  ['BK', 'The Bank of New York Mellon Corporation', 'NYSE'],
  ['COF', 'Capital One Financial Corporation', 'NYSE'],
  ['MET', 'MetLife, Inc.', 'NYSE'],
  ['TRV', 'The Travelers Companies, Inc.', 'NYSE'],
  ['ALL', 'The Allstate Corporation', 'NYSE'],
  ['PCAR', 'PACCAR Inc', 'NASDAQ'],
  ['AIG', 'American International Group, Inc.', 'NYSE'],
  ['DHI', 'D.R. Horton, Inc.', 'NYSE'],
  ['LEN', 'Lennar Corporation', 'NYSE'],
  ['NEM', 'Newmont Corporation', 'NYSE'],
  ['OXY', 'Occidental Petroleum Corporation', 'NYSE'],
  ['EOG', 'EOG Resources, Inc.', 'NYSE'],
  ['WMB', 'The Williams Companies, Inc.', 'NYSE'],
  ['KMI', 'Kinder Morgan, Inc.', 'NYSE'],
  ['OKE', 'ONEOK, Inc.', 'NYSE'],
  ['D', 'Dominion Energy, Inc.', 'NYSE'],
  ['AEP', 'American Electric Power Company, Inc.', 'NASDAQ'],
  ['EXC', 'Exelon Corporation', 'NASDAQ'],
  ['SRE', 'Sempra', 'NYSE'],
  ['XEL', 'Xcel Energy Inc.', 'NASDAQ'],
  ['PEG', 'Public Service Enterprise Group Incorporated', 'NYSE'],
  ['ED', 'Consolidated Edison, Inc.', 'NYSE'],
  ['VLO', 'Valero Energy Corporation', 'NYSE'],
  ['KMB', 'Kimberly-Clark Corporation', 'NYSE'],
  ['GIS', 'General Mills, Inc.', 'NYSE'],
  ['SYY', 'Sysco Corporation', 'NYSE'],
  ['KHC', 'The Kraft Heinz Company', 'NASDAQ'],
  ['MDLZ', 'Mondelez International, Inc.', 'NASDAQ'],
  ['HSY', 'The Hershey Company', 'NYSE'],
  ['STZ', 'Constellation Brands, Inc.', 'NYSE'],
  ['MNST', 'Monster Beverage Corporation', 'NASDAQ'],
  ['KDP', 'Keurig Dr Pepper Inc.', 'NASDAQ'],
  ['ADM', 'Archer-Daniels-Midland Company', 'NYSE'],
  ['KR', 'The Kroger Co.', 'NYSE'],
  ['DG', 'Dollar General Corporation', 'NYSE'],
  ['DLTR', 'Dollar Tree, Inc.', 'NASDAQ'],
  ['TGT', 'Target Corporation', 'NYSE'],
  ['YUM', 'Yum! Brands, Inc.', 'NYSE'],
  ['GWW', 'W.W. Grainger, Inc.', 'NYSE'],
  ['FAST', 'Fastenal Company', 'NASDAQ'],
  ['ODFL', 'Old Dominion Freight Line, Inc.', 'NASDAQ'],
  ['URI', 'United Rentals, Inc.', 'NYSE'],
  ['PWR', 'Quanta Services, Inc.', 'NYSE'],
  ['PCG', 'PG&E Corporation', 'NYSE'],
  ['EW', 'Edwards Lifesciences Corporation', 'NYSE'],
  ['IDXX', 'IDEXX Laboratories, Inc.', 'NASDAQ'],
  ['A', 'Agilent Technologies, Inc.', 'NYSE'],
  ['IQV', 'IQVIA Holdings Inc.', 'NYSE'],
  ['HUM', 'Humana Inc.', 'NYSE'],
  ['CNC', 'Centene Corporation', 'NYSE'],
  ['DXCM', 'DexCom, Inc.', 'NASDAQ'],
  ['MRNA', 'Moderna, Inc.', 'NASDAQ'],
  ['BIIB', 'Biogen Inc.', 'NASDAQ'],
  ['ILMN', 'Illumina, Inc.', 'NASDAQ'],
  ['MTD', 'Mettler-Toledo International Inc.', 'NYSE'],
  ['RMD', 'ResMed Inc.', 'NYSE'],
  ['GEHC', 'GE HealthCare Technologies Inc.', 'NASDAQ'],
  ['CTVA', 'Corteva, Inc.', 'NYSE'],
  ['DOW', 'Dow Inc.', 'NYSE'],
  ['DD', 'DuPont de Nemours, Inc.', 'NYSE'],
  ['PPG', 'PPG Industries, Inc.', 'NYSE'],
  ['SHW', 'The Sherwin-Williams Company', 'NYSE'],
  ['NUE', 'Nucor Corporation', 'NYSE'],
  ['VMC', 'Vulcan Materials Company', 'NYSE'],
  ['MLM', 'Martin Marietta Materials, Inc.', 'NYSE'],
  ['LHX', 'L3Harris Technologies, Inc.', 'NYSE'],
  ['AME', 'AMETEK, Inc.', 'NYSE'],
  ['ROK', 'Rockwell Automation, Inc.', 'NYSE'],
  ['DOV', 'Dover Corporation', 'NYSE'],
  ['FTV', 'Fortive Corporation', 'NYSE'],
  ['XYL', 'Xylem Inc.', 'NYSE'],
  ['CMI', 'Cummins Inc.', 'NYSE'],
  ['OTIS', 'Otis Worldwide Corporation', 'NYSE'],
  ['WAB', 'Westinghouse Air Brake Technologies Corporation', 'NYSE'],
  ['IR', 'Ingersoll Rand Inc.', 'NYSE'],
  ['EFX', 'Equifax Inc.', 'NYSE'],
  ['VRSK', 'Verisk Analytics, Inc.', 'NASDAQ'],
  ['BR', 'Broadridge Financial Solutions, Inc.', 'NYSE'],
  ['PAYX', 'Paychex, Inc.', 'NASDAQ'],
  ['GPN', 'Global Payments Inc.', 'NYSE'],
  ['CDNS', 'Cadence Design Systems, Inc.', 'NASDAQ'],
  ['SNPS', 'Synopsys, Inc.', 'NASDAQ'],
  ['ANSS', 'ANSYS, Inc.', 'NASDAQ'],
  ['FTNT', 'Fortinet, Inc.', 'NASDAQ'],
  ['PANW', 'Palo Alto Networks, Inc.', 'NASDAQ'],
  ['CRWD', 'CrowdStrike Holdings, Inc.', 'NASDAQ'],
  ['WDAY', 'Workday, Inc.', 'NASDAQ'],
  ['TEL', 'TE Connectivity plc', 'NYSE'],
  ['GLW', 'Corning Incorporated', 'NYSE'],
  ['KLAC', 'KLA Corporation', 'NASDAQ'],
  ['LRCX', 'Lam Research Corporation', 'NASDAQ'],
  ['AMAT', 'Applied Materials, Inc.', 'NASDAQ'],
  ['MCHP', 'Microchip Technology Incorporated', 'NASDAQ'],
  ['ON', 'ON Semiconductor Corporation', 'NASDAQ'],
  ['MPWR', 'Monolithic Power Systems, Inc.', 'NASDAQ'],
  ['CDW', 'CDW Corporation', 'NASDAQ'],
  ['KEYS', 'Keysight Technologies, Inc.', 'NYSE'],
  ['TER', 'Teradyne, Inc.', 'NASDAQ'],
  ['HPQ', 'HP Inc.', 'NYSE'],
  ['DELL', 'Dell Technologies Inc.', 'NYSE'],
  ['HPE', 'Hewlett Packard Enterprise Company', 'NYSE'],
  ['NTAP', 'NetApp, Inc.', 'NASDAQ'],
  ['WDC', 'Western Digital Corporation', 'NASDAQ'],
  ['STX', 'Seagate Technology Holdings plc', 'NASDAQ'],
  ['SWKS', 'Skyworks Solutions, Inc.', 'NASDAQ'],
  ['ANET', 'Arista Networks, Inc.', 'NYSE'],
  ['FICO', 'Fair Isaac Corporation', 'NYSE'],
  ['IT', 'Gartner, Inc.', 'NYSE'],
  ['ACGL', 'Arch Capital Group Ltd.', 'NASDAQ'],
  ['WTW', 'Willis Towers Watson Public Limited Company', 'NASDAQ'],
  ['HIG', 'The Hartford Financial Services Group, Inc.', 'NYSE'],
  ['PRU', 'Prudential Financial, Inc.', 'NYSE'],
  ['AMP', 'Ameriprise Financial, Inc.', 'NYSE'],
  ['DFS', 'Discover Financial Services', 'NYSE'],
  ['FITB', 'Fifth Third Bancorp', 'NASDAQ'],
  ['MTB', 'M&T Bank Corporation', 'NYSE'],
  ['HBAN', 'Huntington Bancshares Incorporated', 'NASDAQ'],
  ['RF', 'Regions Financial Corporation', 'NYSE'],
  ['CFG', 'Citizens Financial Group, Inc.', 'NYSE'],
  ['KEY', 'KeyCorp', 'NYSE'],
  ['NTRS', 'Northern Trust Corporation', 'NASDAQ'],
  ['STT', 'State Street Corporation', 'NYSE'],
  ['MSCI', 'MSCI Inc.', 'NYSE'],
  ['MCO', "Moody's Corporation", 'NYSE'],
  ['NDAQ', 'Nasdaq, Inc.', 'NASDAQ'],
  ['CBOE', 'Cboe Global Markets, Inc.', 'BATS'],
  ['TROW', 'T. Rowe Price Group, Inc.', 'NASDAQ'],
  ['INVH', 'Invitation Homes Inc.', 'NYSE'],
  ['EXR', 'Extra Space Storage Inc.', 'NYSE'],
  ['PSA', 'Public Storage', 'NYSE'],
  ['AVB', 'AvalonBay Communities, Inc.', 'NYSE'],
  ['EQR', 'Equity Residential', 'NYSE'],
  ['VICI', 'VICI Properties Inc.', 'NYSE'],
  ['CCI', 'Crown Castle Inc.', 'NYSE'],
  ['SBAC', 'SBA Communications Corporation', 'NASDAQ'],
  ['WY', 'Weyerhaeuser Company', 'NYSE'],
  ['ARE', 'Alexandria Real Estate Equities, Inc.', 'NYSE'],
  ['VTR', 'Ventas, Inc.', 'NYSE'],
  ['MAA', 'Mid-America Apartment Communities, Inc.', 'NYSE'],
  ['ESS', 'Essex Property Trust, Inc.', 'NYSE'],
  ['KIM', 'Kimco Realty Corporation', 'NYSE'],
  ['DTE', 'DTE Energy Company', 'NYSE'],
  ['WEC', 'WEC Energy Group, Inc.', 'NYSE'],
  ['ES', 'Eversource Energy', 'NYSE'],
  ['AEE', 'Ameren Corporation', 'NYSE'],
  ['FE', 'FirstEnergy Corp.', 'NYSE'],
  ['ETR', 'Entergy Corporation', 'NYSE'],
  ['PPL', 'PPL Corporation', 'NYSE'],
  ['CMS', 'CMS Energy Corporation', 'NYSE'],
  ['CNP', 'CenterPoint Energy, Inc.', 'NYSE'],
  ['ATO', 'Atmos Energy Corporation', 'NYSE'],
  ['NRG', 'NRG Energy, Inc.', 'NYSE'],
  ['NEE', 'NextEra Energy, Inc.', 'NYSE'],
  ['LNT', 'Alliant Energy Corporation', 'NASDAQ'],
  ['EVRG', 'Evergy, Inc.', 'NASDAQ'],
  ['AES', 'The AES Corporation', 'NYSE'],
  ['HES', 'Hess Corporation', 'NYSE'],
  ['DVN', 'Devon Energy Corporation', 'NYSE'],
  ['FANG', 'Diamondback Energy, Inc.', 'NASDAQ'],
  ['COP', 'ConocoPhillips', 'NYSE'],
  ['BKR', 'Baker Hughes Company', 'NASDAQ'],
  ['HAL', 'Halliburton Company', 'NYSE'],
  ['CTRA', 'Coterra Energy Inc.', 'NYSE'],
  ['TRGP', 'Targa Resources Corp.', 'NYSE'],
  ['EQT', 'EQT Corporation', 'NYSE'],
  ['LULU', 'Lululemon Athletica Inc.', 'NASDAQ'],
  ['ULTA', 'Ulta Beauty, Inc.', 'NASDAQ'],
  ['BBY', 'Best Buy Co., Inc.', 'NYSE'],
  ['GRMN', 'Garmin Ltd.', 'NYSE'],
  ['POOL', 'Pool Corporation', 'NASDAQ'],
  ['DPZ', "Domino's Pizza, Inc.", 'NASDAQ'],
  ['DRI', 'Darden Restaurants, Inc.', 'NYSE'],
  ['EBAY', 'eBay Inc.', 'NASDAQ'],
  ['EXPE', 'Expedia Group, Inc.', 'NASDAQ'],
  ['ABNB', 'Airbnb, Inc.', 'NASDAQ'],
  ['UBER', 'Uber Technologies, Inc.', 'NYSE'],
  ['DASH', 'DoorDash, Inc.', 'NASDAQ'],
  ['RCL', 'Royal Caribbean Cruises Ltd.', 'NYSE'],
  ['CCL', 'Carnival Corporation & plc', 'NYSE'],
  ['NCLH', 'Norwegian Cruise Line Holdings Ltd.', 'NYSE'],
  ['HLT', 'Hilton Worldwide Holdings Inc.', 'NYSE'],
  ['MGM', 'MGM Resorts International', 'NYSE'],
  ['LVS', 'Las Vegas Sands Corp.', 'NYSE'],
  ['WYNN', 'Wynn Resorts, Limited', 'NASDAQ'],
  ['CZR', 'Caesars Entertainment, Inc.', 'NASDAQ'],
  ['F', 'Ford Motor Company', 'NYSE'],
  ['APTV', 'Aptiv PLC', 'NYSE'],
  ['BWA', 'BorgWarner Inc.', 'NYSE'],
  ['LKQ', 'LKQ Corporation', 'NASDAQ'],
  ['GPC', 'Genuine Parts Company', 'NYSE'],
  ['TSCO', 'Tractor Supply Company', 'NASDAQ'],
  ['WSM', 'Williams-Sonoma, Inc.', 'NYSE'],
  ['NVR', 'NVR, Inc.', 'NYSE'],
  ['PHM', 'PulteGroup, Inc.', 'NYSE'],
  ['MAS', 'Masco Corporation', 'NYSE'],
  ['BLDR', 'Builders FirstSource, Inc.', 'NYSE'],
  ['MHK', 'Mohawk Industries, Inc.', 'NYSE'],
  ['WHR', 'Whirlpool Corporation', 'NYSE'],
  ['SWK', 'Stanley Black & Decker, Inc.', 'NYSE'],
  ['SNA', 'Snap-on Incorporated', 'NYSE'],
  ['LII', 'Lennox International Inc.', 'NYSE'],
  ['ALLE', 'Allegion plc', 'NYSE'],
  ['JCI', 'Johnson Controls International plc', 'NYSE'],
  ['NDSN', 'Nordson Corporation', 'NASDAQ'],
  ['GGG', 'Graco Inc.', 'NYSE'],
  ['PNR', 'Pentair plc', 'NYSE'],
  ['IEX', 'IDEX Corporation', 'NYSE'],
  ['EL', 'The Estée Lauder Companies Inc.', 'NYSE'],
  ['CLX', 'The Clorox Company', 'NYSE'],
  ['CHD', 'Church & Dwight Co., Inc.', 'NYSE'],
  ['TAP', 'Molson Coors Beverage Company', 'NYSE'],
  ['BG', 'Bunge Global SA', 'NYSE'],
  ['HRL', 'Hormel Foods Corporation', 'NYSE'],
  ['CAG', 'Conagra Brands, Inc.', 'NYSE'],
  ['CPB', 'The Campbell Company', 'NYSE'],
  ['SJM', 'The J. M. Smucker Company', 'NYSE'],
  ['MKC', 'McCormick & Company, Incorporated', 'NYSE'],
  ['K', 'Kellanova', 'NYSE'],
  ['TSN', 'Tyson Foods, Inc.', 'NYSE'],
  ['WBA', 'Walgreens Boots Alliance, Inc.', 'NASDAQ'],
  ['DGX', 'Quest Diagnostics Incorporated', 'NYSE'],
  ['LH', 'Labcorp Holdings Inc.', 'NYSE'],
  ['ZBH', 'Zimmer Biomet Holdings, Inc.', 'NYSE'],
  ['STE', 'STERIS plc', 'NYSE'],
  ['BAX', 'Baxter International Inc.', 'NYSE'],
  ['HOLX', 'Hologic, Inc.', 'NASDAQ'],
  ['COO', 'The Cooper Companies, Inc.', 'NASDAQ'],
  ['ALGN', 'Align Technology, Inc.', 'NASDAQ'],
  ['WAT', 'Waters Corporation', 'NYSE'],
  ['PODD', 'Insulet Corporation', 'NASDAQ'],
  ['MOH', 'Molina Healthcare, Inc.', 'NYSE'],
  ['DVA', 'DaVita Inc.', 'NYSE'],
  ['UHS', 'Universal Health Services, Inc.', 'NYSE'],
  ['CAH', 'Cardinal Health, Inc.', 'NYSE'],
  ['COR', 'Cencora, Inc.', 'NYSE'],
  ['CTSH', 'Cognizant Technology Solutions Corporation', 'NASDAQ'],
  ['GEN', 'Gen Digital Inc.', 'NASDAQ'],
  ['AKAM', 'Akamai Technologies, Inc.', 'NASDAQ'],
  ['JNPR', 'Juniper Networks, Inc.', 'NYSE'],
  ['FFIV', 'F5, Inc.', 'NASDAQ'],
  ['ZBRA', 'Zebra Technologies Corporation', 'NASDAQ'],
  ['TDY', 'Teledyne Technologies Incorporated', 'NYSE'],
  ['TYL', 'Tyler Technologies, Inc.', 'NYSE'],
  ['PTC', 'PTC Inc.', 'NASDAQ'],
  ['TXT', 'Textron Inc.', 'NYSE'],
  ['HWM', 'Howmet Aerospace Inc.', 'NYSE'],
  ['AXON', 'Axon Enterprise, Inc.', 'NASDAQ'],
  ['HII', 'Huntington Ingalls Industries, Inc.', 'NYSE'],
  ['LDOS', 'Leidos Holdings, Inc.', 'NYSE'],
  ['J', 'Jacobs Solutions Inc.', 'NYSE'],
  ['ROL', 'Rollins, Inc.', 'NYSE'],
  ['CHRW', 'C.H. Robinson Worldwide, Inc.', 'NASDAQ'],
  ['EXPD', 'Expeditors International of Washington, Inc.', 'NASDAQ'],
  ['JBHT', 'J.B. Hunt Transport Services, Inc.', 'NASDAQ'],
  ['UPS', 'United Parcel Service, Inc.', 'NYSE'],
  ['LUV', 'Southwest Airlines Co.', 'NYSE'],
  ['DAL', 'Delta Air Lines, Inc.', 'NYSE'],
  ['UAL', 'United Airlines Holdings, Inc.', 'NASDAQ'],
  ['AAL', 'American Airlines Group Inc.', 'NASDAQ'],
  ['DAY', 'Dayforce, Inc.', 'NYSE'],
  ['CPAY', 'Corpay, Inc.', 'NYSE'],
  ['JKHY', 'Jack Henry & Associates, Inc.', 'NASDAQ'],
  ['MKTX', 'MarketAxess Holdings Inc.', 'NASDAQ'],
  ['NWSA', 'News Corporation (Class A)', 'NASDAQ'],
  ['FOXA', 'Fox Corporation (Class A)', 'NASDAQ'],
  ['PARA', 'Paramount Global', 'NASDAQ'],
  ['WBD', 'Warner Bros. Discovery, Inc.', 'NASDAQ'],
  ['DIS', 'The Walt Disney Company', 'NYSE'],
  ['OMC', 'Omnicom Group Inc.', 'NYSE'],
  ['IPG', 'The Interpublic Group of Companies, Inc.', 'NYSE'],
  ['TTWO', 'Take-Two Interactive Software, Inc.', 'NASDAQ'],
  ['EA', 'Electronic Arts Inc.', 'NASDAQ'],
  ['LYV', 'Live Nation Entertainment, Inc.', 'NYSE'],
  ['TMUS', 'T-Mobile US, Inc.', 'NASDAQ'],
  ['CHTR', 'Charter Communications, Inc.', 'NASDAQ'],
  ['VTRS', 'Viatris Inc.', 'NASDAQ'],
  ['INCY', 'Incyte Corporation', 'NASDAQ'],
  ['CRL', 'Charles River Laboratories International, Inc.', 'NYSE'],
  ['TECH', 'Bio-Techne Corporation', 'NASDAQ'],
  ['BALL', 'Ball Corporation', 'NYSE'],
  ['AMCR', 'Amcor plc', 'NYSE'],
  ['IP', 'International Paper Company', 'NYSE'],
  ['PKG', 'Packaging Corporation of America', 'NYSE'],
  ['AVY', 'Avery Dennison Corporation', 'NYSE'],
  ['CF', 'CF Industries Holdings, Inc.', 'NYSE'],
  ['MOS', 'The Mosaic Company', 'NYSE'],
  ['LYB', 'LyondellBasell Industries N.V.', 'NYSE'],
  ['ALB', 'Albemarle Corporation', 'NYSE'],
  ['IFF', 'International Flavors & Fragrances Inc.', 'NYSE'],
  ['CE', 'Celanese Corporation', 'NYSE'],
  ['EMN', 'Eastman Chemical Company', 'NYSE'],
  ['FMC', 'FMC Corporation', 'NYSE'],
  ['STLD', 'Steel Dynamics, Inc.', 'NASDAQ'],
  ['RS', 'Reliance, Inc.', 'NYSE'],
  ['CSGP', 'CoStar Group, Inc.', 'NASDAQ'],
  ['CBRE', 'CBRE Group, Inc.', 'NYSE'],
  ['MTCH', 'Match Group, Inc.', 'NASDAQ'],
  ['PINS', 'Pinterest, Inc.', 'NYSE'],
  ['ENPH', 'Enphase Energy, Inc.', 'NASDAQ'],
  ['FSLR', 'First Solar, Inc.', 'NASDAQ'],
  ['GNRC', 'Generac Holdings Inc.', 'NYSE'],
  ['DECK', 'Deckers Outdoor Corporation', 'NYSE'],
  ['RL', 'Ralph Lauren Corporation', 'NYSE'],
  ['TPR', 'Tapestry, Inc.', 'NYSE'],
  ['VFC', 'V.F. Corporation', 'NYSE'],
  ['HAS', 'Hasbro, Inc.', 'NASDAQ'],
  ['MAT', 'Mattel, Inc.', 'NASDAQ'],
  ['NWS', 'News Corporation (Class B)', 'NASDAQ'],
  ['FOX', 'Fox Corporation (Class B)', 'NASDAQ'],
  ['SMCI', 'Super Micro Computer, Inc.', 'NASDAQ'],
  ['PLTR', 'Palantir Technologies Inc.', 'NASDAQ'],
  ['KVUE', 'Kenvue Inc.', 'NYSE'],
  ['GDDY', 'GoDaddy Inc.', 'NYSE'],
  ['VLTO', 'Veralto Corporation', 'NYSE'],
  ['SOLV', 'Solventum Corporation', 'NYSE'],
  ['ERIE', 'Erie Indemnity Company', 'NASDAQ'],
  ['BRO', 'Brown & Brown, Inc.', 'NYSE'],
  ['GL', 'Globe Life Inc.', 'NYSE'],
  ['L', 'Loews Corporation', 'NYSE'],
  ['CINF', 'Cincinnati Financial Corporation', 'NASDAQ'],
  ['WRB', 'W. R. Berkley Corporation', 'NYSE'],
  ['RJF', 'Raymond James Financial, Inc.', 'NYSE'],
  ['SYF', 'Synchrony Financial', 'NYSE'],
  ['FDS', 'FactSet Research Systems Inc.', 'NYSE'],
  ['EPAM', 'EPAM Systems, Inc.', 'NYSE'],
  ['JBL', 'Jabil Inc.', 'NYSE'],
  ['TRMB', 'Trimble Inc.', 'NASDAQ'],
  ['HuBB', 'Hubbell Incorporated', 'NYSE'],
  ['AWK', 'American Water Works Company, Inc.', 'NYSE'],
  ['WTRG', 'Essential Utilities, Inc.', 'NYSE'],
  ['PNW', 'Pinnacle West Capital Corporation', 'NYSE'],
  ['NI', 'NiSource Inc.', 'NYSE'],
  ['APA', 'APA Corporation', 'NASDAQ'],
  ['EG', 'Everest Group, Ltd.', 'NYSE'],
  ['RVTY', 'Revvity, Inc.', 'NYSE'],
  ['TFX', 'Teleflex Incorporated', 'NYSE'],
  ['HSIC', 'Henry Schein, Inc.', 'NASDAQ'],
  ['XRAY', 'DENTSPLY SIRONA Inc.', 'NASDAQ'],
  ['BEN', 'Franklin Resources, Inc.', 'NYSE'],
  ['IVZ', 'Invesco Ltd.', 'NYSE'],
  ['NWL', 'Newell Brands Inc.', 'NASDAQ'],
  ['REG', 'Regency Centers Corporation', 'NASDAQ'],
  ['FRT', 'Federal Realty Investment Trust', 'NYSE'],
  ['BXP', 'BXP, Inc.', 'NYSE'],
  ['HST', 'Host Hotels & Resorts, Inc.', 'NASDAQ'],
  ['UDR', 'UDR, Inc.', 'NYSE'],
  ['CPT', 'Camden Property Trust', 'NYSE'],
  ['DOC', 'Healthpeak Properties, Inc.', 'NYSE'],
  ['IRM', 'Iron Mountain Incorporated', 'NYSE'],
  ['LW', 'Lamb Weston Holdings, Inc.', 'NYSE'],
  ['AOS', 'A. O. Smith Corporation', 'NYSE'],
  ['KMX', 'CarMax, Inc.', 'NYSE'],
  ['AIZ', 'Assurant, Inc.', 'NYSE'],
  ['BF-B', 'Brown-Forman Corporation (Class B)', 'NYSE'],
  ['PAYC', 'Paycom Software, Inc.', 'NYSE'],
  ['WST', 'West Pharmaceutical Services, Inc.', 'NYSE'],
  ['VRSN', 'VeriSign, Inc.', 'NASDAQ'],
  ['QRVO', 'Qorvo, Inc.', 'NASDAQ'],
]);

// ── Top cryptocurrencies by market cap (Yahoo `-USD` pairs) ───────────────────
// Named by the coin itself (the USD quote lives in the currency column) so a
// misspelled fuzzy search like "etherium" clears the trigram threshold instead
// of being diluted by a trailing " USD".
const CRYPTO: Entry[] = (
  [
    ['BTC-USD', 'Bitcoin'],
    ['ETH-USD', 'Ethereum'],
    ['USDT-USD', 'Tether USDt'],
    ['BNB-USD', 'BNB'],
    ['SOL-USD', 'Solana'],
    ['USDC-USD', 'USD Coin'],
    ['XRP-USD', 'XRP'],
    ['DOGE-USD', 'Dogecoin'],
    ['ADA-USD', 'Cardano'],
    ['TRX-USD', 'TRON'],
    ['AVAX-USD', 'Avalanche'],
    ['SHIB-USD', 'Shiba Inu'],
    ['DOT-USD', 'Polkadot'],
    ['LINK-USD', 'Chainlink'],
    ['BCH-USD', 'Bitcoin Cash'],
    ['LTC-USD', 'Litecoin'],
    ['MATIC-USD', 'Polygon'],
    ['XLM-USD', 'Stellar'],
    ['UNI7083-USD', 'Uniswap'],
    ['ATOM-USD', 'Cosmos'],
    ['ETC-USD', 'Ethereum Classic'],
    ['XMR-USD', 'Monero'],
    ['FIL-USD', 'Filecoin'],
    ['APT-USD', 'Aptos'],
    ['ARB-USD', 'Arbitrum'],
    ['NEAR-USD', 'NEAR Protocol'],
    ['OP-USD', 'Optimism'],
    ['VET-USD', 'VeChain'],
    ['ICP-USD', 'Internet Computer'],
    ['HBAR-USD', 'Hedera'],
  ] as const
).map(([ref, name]) => entry('crypto', ref, name, 'CCC', 'USD'));

// ── Major FX pairs (Yahoo `=X`), currency = quote currency ───────────────────
const FX: Entry[] = [
  entry('fx', 'EURUSD=X', 'EUR/USD', 'CCY', 'USD'),
  entry('fx', 'GBPUSD=X', 'GBP/USD', 'CCY', 'USD'),
  entry('fx', 'USDJPY=X', 'USD/JPY', 'CCY', 'JPY'),
  entry('fx', 'USDCHF=X', 'USD/CHF', 'CCY', 'CHF'),
  entry('fx', 'AUDUSD=X', 'AUD/USD', 'CCY', 'USD'),
  entry('fx', 'USDCAD=X', 'USD/CAD', 'CCY', 'CAD'),
  entry('fx', 'EURGBP=X', 'EUR/GBP', 'CCY', 'GBP'),
];

// ── Key commodities (Yahoo futures `=F`) ─────────────────────────────────────
const COMMODITIES: Entry[] = [
  entry('commodity', 'GC=F', 'Gold', 'CMX', 'USD'),
  entry('commodity', 'SI=F', 'Silver', 'CMX', 'USD'),
  entry('commodity', 'BZ=F', 'Brent Crude Oil', 'NYM', 'USD'),
  entry('commodity', 'CL=F', 'Crude Oil (WTI)', 'NYM', 'USD'),
  entry('commodity', 'HG=F', 'Copper', 'CMX', 'USD'),
  entry('commodity', 'NG=F', 'Natural Gas', 'NYM', 'USD'),
];

/**
 * Full shipped catalog seed. Order is irrelevant (upsert is per-row idempotent),
 * but grouping keeps the file auditable against §6.2(c).
 */
export const CATALOG_SEED_ENTRIES: readonly Entry[] = [
  ...INDICES,
  ...ETFS,
  ...DAX40,
  ...ATX20,
  ...SP500,
  ...CRYPTO,
  ...FX,
  ...COMMODITIES,
];
