/**
 * Pure serialization of a per-year tax report (V5-P4b, issue #583) to CSV. No
 * I/O: a deterministic function over the exact {@link TaxYearReportResponse}
 * that feeds the on-screen report, so the download can never drift from the
 * screen — one source of truth, no recomputation. Tested directly.
 *
 * The file is a sequence of labeled sections separated by a blank line so a
 * single download covers the whole year: `Summary` (year totals), `Germany`
 * (present only when the year carries DE-taxed rows — the Sparer-Pauschbetrag,
 * both §20 Abs. 6 loss pots in→out, and the KapESt/Soli split), `Positions`
 * (per-asset totals), then the `Sells` and `Dividends` drill-down rows, and a
 * final `Disclaimer` section carrying the owner-mandated estimates-only notice.
 *
 * Number format (documented in the endpoint contract too): a period decimal
 * separator, no thousands grouping, money to 2 decimals — spreadsheet-safe on
 * a plain CSV import in any locale. Dates are ISO `YYYY-MM-DD`.
 */
import type { TaxExportLocale, TaxYearReportResponse } from '@bettertrack/contracts';

interface CsvCopy {
  section: string;
  summary: {
    title: string;
    year: string;
    realized: string;
    dividends: string;
    withheld: string;
    refunded: string;
    net: string;
  };
  de: {
    title: string;
    allowanceUsed: string;
    allowanceRemaining: string;
    aktienIn: string;
    aktienOut: string;
    sonstigeIn: string;
    sonstigeOut: string;
    kapest: string;
    soli: string;
  };
  positions: {
    title: string;
    symbol: string;
    name: string;
    realized: string;
    dividends: string;
    tax: string;
  };
  sells: {
    title: string;
    symbol: string;
    name: string;
    date: string;
    quantity: string;
    proceeds: string;
    costBasis: string;
    realized: string;
    taxMode: string;
    tax: string;
  };
  dividends: {
    title: string;
    symbol: string;
    name: string;
    date: string;
    gross: string;
    taxMode: string;
    tax: string;
  };
  disclaimer: {
    title: string;
    text: string;
  };
}

/**
 * Localized headers/labels for the two shipped locales (EN + DE). Server-side
 * copy, like the notification email copy table — the CSV is generated by the
 * API, so its strings live here rather than in the web i18n bundle.
 */
const CSV_COPY: Record<TaxExportLocale, CsvCopy> = {
  en: {
    section: 'Section',
    summary: {
      title: 'Summary',
      year: 'Year',
      realized: 'Realized P/L (EUR)',
      dividends: 'Dividends gross (EUR)',
      withheld: 'Tax withheld (EUR)',
      refunded: 'Tax refunded (EUR)',
      net: 'Net tax (EUR)',
    },
    de: {
      title: 'Germany (Abgeltungsteuer)',
      allowanceUsed: 'Allowance used (EUR)',
      allowanceRemaining: 'Allowance remaining (EUR)',
      aktienIn: 'Share-loss pot in (EUR)',
      aktienOut: 'Share-loss pot out (EUR)',
      sonstigeIn: 'Other-loss pot in (EUR)',
      sonstigeOut: 'Other-loss pot out (EUR)',
      kapest: 'KapESt (EUR)',
      soli: 'Soli (EUR)',
    },
    positions: {
      title: 'Positions',
      symbol: 'Symbol',
      name: 'Name',
      realized: 'Realized P/L (EUR)',
      dividends: 'Dividends gross (EUR)',
      tax: 'Tax (EUR)',
    },
    sells: {
      title: 'Sells',
      symbol: 'Symbol',
      name: 'Name',
      date: 'Date',
      quantity: 'Quantity',
      proceeds: 'Proceeds (EUR)',
      costBasis: 'Cost basis (EUR)',
      realized: 'Realized P/L (EUR)',
      taxMode: 'Tax mode',
      tax: 'Tax (EUR)',
    },
    dividends: {
      title: 'Dividends',
      symbol: 'Symbol',
      name: 'Name',
      date: 'Date',
      gross: 'Gross (EUR)',
      taxMode: 'Tax mode',
      tax: 'Tax (EUR)',
    },
    disclaimer: {
      title: 'Disclaimer',
      text: 'Estimates for your personal overview only — not tax advice, no guarantee of correctness, not a filing document.',
    },
  },
  de: {
    section: 'Abschnitt',
    summary: {
      title: 'Zusammenfassung',
      year: 'Jahr',
      realized: 'Realisierter G/V (EUR)',
      dividends: 'Dividenden brutto (EUR)',
      withheld: 'Einbehaltene Steuer (EUR)',
      refunded: 'Erstattete Steuer (EUR)',
      net: 'Netto-Steuer (EUR)',
    },
    de: {
      title: 'Deutschland (Abgeltungsteuer)',
      allowanceUsed: 'Genutzter Pauschbetrag (EUR)',
      allowanceRemaining: 'Verbleibender Pauschbetrag (EUR)',
      aktienIn: 'Aktien-Verlusttopf ein (EUR)',
      aktienOut: 'Aktien-Verlusttopf aus (EUR)',
      sonstigeIn: 'Sonstiger Verlusttopf ein (EUR)',
      sonstigeOut: 'Sonstiger Verlusttopf aus (EUR)',
      kapest: 'KapESt (EUR)',
      soli: 'Soli (EUR)',
    },
    positions: {
      title: 'Positionen',
      symbol: 'Symbol',
      name: 'Name',
      realized: 'Realisierter G/V (EUR)',
      dividends: 'Dividenden brutto (EUR)',
      tax: 'Steuer (EUR)',
    },
    sells: {
      title: 'Verkäufe',
      symbol: 'Symbol',
      name: 'Name',
      date: 'Datum',
      quantity: 'Anzahl',
      proceeds: 'Erlös (EUR)',
      costBasis: 'Einstand (EUR)',
      realized: 'Realisierter G/V (EUR)',
      taxMode: 'Steuermodus',
      tax: 'Steuer (EUR)',
    },
    dividends: {
      title: 'Dividenden',
      symbol: 'Symbol',
      name: 'Name',
      date: 'Datum',
      gross: 'Brutto (EUR)',
      taxMode: 'Steuermodus',
      tax: 'Steuer (EUR)',
    },
    disclaimer: {
      title: 'Haftungsausschluss',
      text: 'Schätzwerte nur für deine persönliche Übersicht — keine Steuerberatung, keine Gewähr für Richtigkeit, kein Dokument für die Steuererklärung.',
    },
  },
};

/** RFC-4180 field: quote when it holds a comma, quote, or newline; double inner quotes. */
function csvField(value: string | number): string {
  const s = String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function csvRow(cells: (string | number)[]): string {
  return cells.map(csvField).join(',');
}

/** Money to 2 decimals with a period separator (matches the on-screen 2-dp render). */
function money(amount: number): string {
  return amount.toFixed(2);
}

/** A quantity as a plain decimal (period separator, trailing zeros trimmed, no exponent). */
function quantity(value: number): string {
  return value.toFixed(8).replace(/\.?0+$/, '');
}

/** The date portion of an ISO datetime — spreadsheet-safe `YYYY-MM-DD`. */
function isoDate(iso: string): string {
  return iso.slice(0, 10);
}

/** A frozen tax-mode string cell (`null` on pre-engine rows renders empty). */
function taxModeCell(mode: string | null): string {
  return mode ?? '';
}

/** An optional EUR tax cell (`null` renders empty, not `0.00`). */
function optMoney(amount: number | null): string {
  return amount === null ? '' : money(amount);
}

/**
 * Serialize one year's report to CSV. `locale` selects header language only;
 * every number is copied verbatim from `report`.
 */
export function serializeTaxYearReportCsv(
  report: TaxYearReportResponse,
  locale: TaxExportLocale = 'en',
): string {
  const c = CSV_COPY[locale];
  const lines: string[] = [];
  const s = report.summary;

  // ── Summary ──
  lines.push(csvRow([c.section, c.summary.title]));
  lines.push(
    csvRow([
      c.summary.year,
      c.summary.realized,
      c.summary.dividends,
      c.summary.withheld,
      c.summary.refunded,
      c.summary.net,
    ]),
  );
  lines.push(
    csvRow([
      s.year,
      money(s.realizedPnlEur),
      money(s.dividendsGrossEur),
      money(s.taxWithheldEur),
      money(s.taxRefundedEur),
      money(s.taxNetEur),
    ]),
  );

  // ── Germany (only when the year carries DE-taxed rows) ──
  if (s.de) {
    lines.push('');
    lines.push(csvRow([c.section, c.de.title]));
    lines.push(
      csvRow([
        c.de.allowanceUsed,
        c.de.allowanceRemaining,
        c.de.aktienIn,
        c.de.aktienOut,
        c.de.sonstigeIn,
        c.de.sonstigeOut,
        c.de.kapest,
        c.de.soli,
      ]),
    );
    lines.push(
      csvRow([
        money(s.de.allowanceUsedEur),
        money(s.de.allowanceRemainingEur),
        money(s.de.aktienPotInEur),
        money(s.de.aktienPotOutEur),
        money(s.de.sonstigePotInEur),
        money(s.de.sonstigePotOutEur),
        money(s.de.kapestEur),
        money(s.de.soliEur),
      ]),
    );
  }

  // ── Positions (per-asset totals) ──
  lines.push('');
  lines.push(csvRow([c.section, c.positions.title]));
  lines.push(
    csvRow([
      c.positions.symbol,
      c.positions.name,
      c.positions.realized,
      c.positions.dividends,
      c.positions.tax,
    ]),
  );
  for (const p of report.positions) {
    lines.push(
      csvRow([
        p.asset.symbol,
        p.asset.name,
        money(p.realizedPnlEur),
        money(p.dividendsGrossEur),
        money(p.taxEur),
      ]),
    );
  }

  // ── Sells drill-down ──
  lines.push('');
  lines.push(csvRow([c.section, c.sells.title]));
  lines.push(
    csvRow([
      c.sells.symbol,
      c.sells.name,
      c.sells.date,
      c.sells.quantity,
      c.sells.proceeds,
      c.sells.costBasis,
      c.sells.realized,
      c.sells.taxMode,
      c.sells.tax,
    ]),
  );
  for (const p of report.positions) {
    for (const sell of p.sells) {
      lines.push(
        csvRow([
          p.asset.symbol,
          p.asset.name,
          isoDate(sell.executedAt),
          quantity(sell.quantity),
          money(sell.proceedsEur),
          money(sell.costBasisEur),
          money(sell.realizedPnlEur),
          taxModeCell(sell.taxMode),
          optMoney(sell.taxAmountEur),
        ]),
      );
    }
  }

  // ── Dividends drill-down ──
  lines.push('');
  lines.push(csvRow([c.section, c.dividends.title]));
  lines.push(
    csvRow([
      c.dividends.symbol,
      c.dividends.name,
      c.dividends.date,
      c.dividends.gross,
      c.dividends.taxMode,
      c.dividends.tax,
    ]),
  );
  for (const p of report.positions) {
    for (const dividend of p.dividends) {
      lines.push(
        csvRow([
          p.asset.symbol,
          p.asset.name,
          isoDate(dividend.executedAt),
          money(dividend.grossAmountEur),
          taxModeCell(dividend.taxMode),
          optMoney(dividend.taxAmountEur),
        ]),
      );
    }
  }

  // ── Disclaimer (owner-mandated liability framing, #635) ──
  // A final labeled section so the export carries the same estimates-only notice
  // the on-screen report shows. Its own section (blank-line separated) never
  // disturbs the parsing of the data rows above.
  lines.push('');
  lines.push(csvRow([c.section, c.disclaimer.title]));
  lines.push(csvRow([c.disclaimer.text]));

  // Trailing CRLF so the last record is terminated (RFC-4180 friendly).
  return lines.join('\r\n') + '\r\n';
}

/** The download filename for a year's tax-report CSV. */
export function taxReportCsvFilename(year: number): string {
  return `tax-report-${year}.csv`;
}
