#!/usr/bin/env bash
# Shared, machine-readable backup status helpers.
#
# The status file is deliberately a conservative key=value format: values are
# generated by these scripts, keys are schema-versioned, and readers never
# source the file as shell code. Updates are serialized and atomically renamed
# so Docker health probes cannot tear an offsite or restore-drill update.

bt_backup_status_file() {
    local backup_dir
    backup_dir="${BACKUP_DIR:-${BT_BACKUP_SOURCE_DIR:-/backups}}"
    printf '%s\n' "${BT_BACKUP_STATUS_FILE:-${backup_dir}/backup-status.env}"
}

bt_status_get() {
    local file key value
    file="$(bt_backup_status_file)"
    key="$1"
    [ -r "${file}" ] || return 1
    value="$(
        awk -F= -v wanted="${key}" '
            $1 == wanted {
                value = substr($0, length($1) + 2)
                found = 1
            }
            END {
                if (found) print value
                else exit 1
            }
        ' "${file}"
    )" || return 1
    printf '%s\n' "${value}"
}

bt_status_update() {
    local file directory lock_file temp_file line existing_key update update_key update_value
    local lock_fd updated content existing_content status_code
    local -a updates
    updates=("$@")
    file="$(bt_backup_status_file)"
    directory="$(dirname "${file}")"
    lock_file="${file}.lock"
    temp_file=''
    content=$'schema_version=1\n'
    existing_content=''
    status_code=0

    if ! mkdir -p "${directory}"; then
        echo "bettertrack-backup-status: could not create status directory ${directory}" >&2
        return 1
    fi

    for update in "${updates[@]}"; do
        update_key="${update%%=*}"
        update_value="${update#*=}"
        if [[ ! "${update_key}" =~ ^[a-z][a-z0-9_]*$ ]] ||
            [[ "${update_value}" == *$'\n'* ]] ||
            [[ "${update_value}" == *$'\r'* ]]; then
            echo "bettertrack-backup-status: refused invalid status update" >&2
            return 1
        fi
    done

    if ! exec {lock_fd}>"${lock_file}"; then
        echo "bettertrack-backup-status: could not open lock file ${lock_file}" >&2
        return 1
    fi
    if ! flock -w 5 "${lock_fd}"; then
        echo "bettertrack-backup-status: timed out waiting for ${lock_file}" >&2
        exec {lock_fd}>&-
        return 1
    fi

    if ! temp_file="$(mktemp "${directory}/.bettertrack-backup-status.XXXXXX")"; then
        echo "bettertrack-backup-status: could not create a temporary status file" >&2
        status_code=1
    fi

    if [ "${status_code}" -eq 0 ] && [ -e "${file}" ]; then
        if ! existing_content="$(cat -- "${file}")"; then
            echo "bettertrack-backup-status: could not read existing status file ${file}" >&2
            status_code=1
        else
            while IFS= read -r line || [ -n "${line}" ]; do
                existing_key="${line%%=*}"
                [[ "${existing_key}" =~ ^[a-z][a-z0-9_]*$ ]] || continue
                [ "${existing_key}" != 'schema_version' ] || continue
                updated=false
                for update in "${updates[@]}"; do
                    update_key="${update%%=*}"
                    if [ "${existing_key}" = "${update_key}" ]; then
                        updated=true
                        break
                    fi
                done
                [ "${updated}" = true ] || content+="${line}"$'\n'
            done <<< "${existing_content}"
        fi
    fi

    if [ "${status_code}" -eq 0 ]; then
        for update in "${updates[@]}"; do
            content+="${update}"$'\n'
        done
    fi

    if [ "${status_code}" -eq 0 ] && ! printf '%s' "${content}" > "${temp_file}"; then
        echo "bettertrack-backup-status: could not write temporary status file ${temp_file}" >&2
        status_code=1
    fi
    # 0644, not 0640: the scheduler runs as root, while the api container runs as
    # the unprivileged `bettertrack` user and mounts this volume READ-ONLY to
    # project the admin readiness tile (#1406 W1). Group-only read left the api
    # with EACCES, which its fail-soft path could only report as "unreadable".
    # Nothing here is a secret — the file holds freshness epochs, outcome tags, an
    # artifact name, a size and a checksum, all of which the operator already sees.
    # Verify in production with:
    #   docker compose exec api cat /status/backup-status.env
    if [ "${status_code}" -eq 0 ] && ! chmod 0644 "${temp_file}"; then
        echo "bettertrack-backup-status: could not set permissions on ${temp_file}" >&2
        status_code=1
    fi
    if [ "${status_code}" -eq 0 ]; then
        if mv -f "${temp_file}" "${file}"; then
            temp_file=''
        else
            echo "bettertrack-backup-status: could not replace status file ${file}" >&2
            status_code=1
        fi
    fi

    if [ -n "${temp_file}" ] && ! rm -f -- "${temp_file}"; then
        echo "bettertrack-backup-status: could not remove temporary file ${temp_file}" >&2
        status_code=1
    fi

    if ! flock -u "${lock_fd}"; then
        echo "bettertrack-backup-status: could not release lock ${lock_file}" >&2
        status_code=1
    fi
    if ! exec {lock_fd}>&-; then
        echo "bettertrack-backup-status: could not close lock ${lock_file}" >&2
        status_code=1
    fi
    return "${status_code}"
}
