#!/usr/bin/env bash
# Shared, machine-readable backup status helpers.
#
# The status file is deliberately a conservative key=value format: values are
# generated by these scripts, keys are schema-versioned, and readers never
# source the file as shell code. Updates are serialized and atomically renamed
# so Docker health probes cannot tear an offsite or restore-drill update.

bt_backup_status_file() {
    local backup_dir
    backup_dir="${BACKUP_DIR:-${BT_BACKUP_SOURCE_DIR:-/backups}}"
    printf '%s\n' "${BT_BACKUP_STATUS_FILE:-${backup_dir}/backup-status.env}"
}

bt_status_get() {
    local file key value
    file="$(bt_backup_status_file)"
    key="$1"
    [ -r "${file}" ] || return 1
    value="$(
        awk -F= -v wanted="${key}" '
            $1 == wanted {
                value = substr($0, length($1) + 2)
                found = 1
            }
            END {
                if (found) print value
                else exit 1
            }
        ' "${file}"
    )" || return 1
    printf '%s\n' "${value}"
}

bt_status_update() {
    local file directory lock_file temp_file line existing_key update update_key update_value
    local lock_fd updated
    local -a updates
    updates=("$@")
    file="$(bt_backup_status_file)"
    directory="$(dirname "${file}")"
    lock_file="${file}.lock"

    mkdir -p "${directory}"

    for update in "${updates[@]}"; do
        update_key="${update%%=*}"
        update_value="${update#*=}"
        if [[ ! "${update_key}" =~ ^[a-z][a-z0-9_]*$ ]] ||
            [[ "${update_value}" == *$'\n'* ]] ||
            [[ "${update_value}" == *$'\r'* ]]; then
            echo "bettertrack-backup-status: refused invalid status update" >&2
            return 1
        fi
    done

    exec {lock_fd}>"${lock_file}"
    if ! flock -w 5 "${lock_fd}"; then
        echo "bettertrack-backup-status: timed out waiting for ${lock_file}" >&2
        exec {lock_fd}>&-
        return 1
    fi

    temp_file="$(mktemp "${directory}/.bettertrack-backup-status.XXXXXX")"
    {
        printf 'schema_version=1\n'
        if [ -r "${file}" ]; then
            while IFS= read -r line || [ -n "${line}" ]; do
                existing_key="${line%%=*}"
                [[ "${existing_key}" =~ ^[a-z][a-z0-9_]*$ ]] || continue
                [ "${existing_key}" != 'schema_version' ] || continue
                updated=false
                for update in "${updates[@]}"; do
                    update_key="${update%%=*}"
                    if [ "${existing_key}" = "${update_key}" ]; then
                        updated=true
                        break
                    fi
                done
                [ "${updated}" = true ] || printf '%s\n' "${line}"
            done < "${file}"
        fi
        for update in "${updates[@]}"; do
            printf '%s\n' "${update}"
        done
    } > "${temp_file}"
    chmod 0640 "${temp_file}"
    mv -f "${temp_file}" "${file}"

    flock -u "${lock_fd}"
    exec {lock_fd}>&-
}
